// app/sitemap.js
// Dynamic XML Sitemap - Auto-generated
// Auto-submitted to Google Search Console for indexing

const BASE_URL = 'https://skilldrills.online';

const categoryPages = [
  { path: '/', priority: 1.0, changefreq: 'daily' },
  { path: '/drills/academic', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/cognitive', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/fps', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/memory', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/motor', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/physical', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/visual', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/visual-tracking', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills', priority: 0.9, changefreq: 'weekly' },
  { path: '/drills/reaction-speed', priority: 0.9, changefreq: 'weekly' },
];

const drillRoutes = [
  { path: '/drills/academic/comprehension/inference-drill', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/comprehension/reading-comprehension', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/math-speed/Math-Reaction', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/math-speed/mental-math', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/reading-speed/peripheral-reader', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/reading-speed/rsvp-reader', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/reading-speed/speed-reader', category: 'academic', priority: 0.9 },
  { path: '/drills/academic/writing-speed/typing-test', category: 'academic', priority: 0.9 },
  { path: '/drills/cognitive/attention/batch-processing', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/concentration-stamina', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/divided-attention', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/multi-tasking', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/selective-attention', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/sustained-attention', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/attention/switch-cost', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/focus/concentration-grid', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/focus/distraction-fighter', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/memory/card-matching', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/memory/memory-sequence', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/memory/pattern-recognition', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/problem-solving/logic-puzzles', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/problem-solving/priority-sorting', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/problem-solving/sudoku', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/problem-solving/tower-of-hanoi', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/processing-speed/reaction-time', category: 'cognitive', priority: 0.85 },
  { path: '/drills/cognitive/processing-speed/symbol-matching', category: 'cognitive', priority: 0.85 },
  { path: '/drills/fps/180-degree-awareness', category: 'fps', priority: 1 },
  { path: '/drills/fps/angle-hold-trainer', category: 'fps', priority: 1 },
  { path: '/drills/fps/anti-strafe-jitter-duel', category: 'fps', priority: 1 },
  { path: '/drills/fps/anti-zigzag-movement-trainer', category: 'fps', priority: 1 },
  { path: '/drills/fps/flick-shot-training', category: 'fps', priority: 1 },
  { path: '/drills/fps/flow-state', category: 'fps', priority: 1 },
  { path: '/drills/fps/instant-response', category: 'fps', priority: 1 },
  { path: '/drills/fps/micro-correction-precision', category: 'fps', priority: 1 },
  { path: '/drills/fps/pro-smooth-pursuit', category: 'fps', priority: 1 },
  { path: '/drills/fps/reactive-sphere-tracking', category: 'fps', priority: 1 },
  { path: '/drills/fps/recoil-control', category: 'fps', priority: 1 },
  { path: '/drills/fps/strafe-tracking', category: 'fps', priority: 1 },
  { path: '/drills/fps/target-acquisition', category: 'fps', priority: 1 },
  { path: '/drills/fps/target-prioritization', category: 'fps', priority: 1 },
  { path: '/drills/fps/target-switching-swarm', category: 'fps', priority: 1 },
  { path: '/drills/fps/vertical-air-track', category: 'fps', priority: 1 },
  { path: '/drills/memory/associative-memory/concept-linking', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/associative-memory/name-face', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/associative-memory/sound-pattern', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/long-term-memory/image-association', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/long-term-memory/paired-associates', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/short-term-memory/color-sequence', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/short-term-memory/digit-span', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/short-term-memory/word-recall', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/spatial-memory/grid-memorization', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/spatial-memory/object-location', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/spatial-memory/path-tracing', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/working-memory/n-back', category: 'memory', priority: 0.85 },
  { path: '/drills/memory/working-memory/sentence-span', category: 'memory', priority: 0.85 },
  { path: '/drills/motor/hand-eye-coordination/aim-trainer', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/hand-eye-coordination/click-accuracy', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/hand-eye-coordination/drag-and-drop', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/hand-eye-coordination/kinetic-target-tracking', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/hand-eye-coordination/precision-flick-shot', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/movement-speed/finger-sequencing', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/movement-speed/gesture-speed', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/movement-speed/keyboard-recognition', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/movement-speed/rapid-tapping', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/precision-control/fine-motor', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/precision-control/steady-hand', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/precision-control/tracing', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/timing-accuracy/stopwatch-click', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/timing-accuracy/synchronization', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/timing-accuracy/time-estimation', category: 'motor', priority: 0.9 },
  { path: '/drills/motor/timing-accuracy/velocity-matcher', category: 'motor', priority: 0.9 },
  { path: '/drills/physical/balance-training/dynamic-balance', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/balance-training/single-leg-hold', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/balance-training/stability-challenge', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/coordination/complex-pattern', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/coordination/cross-body-movement', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/coordination/dynamic-grid-evasion', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/fitness/agility-ladder', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/fitness/jump-sequence', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/fitness/speed-drill', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/reflex-training/drop-catch', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/reflex-training/peripheral-threat-sweeper', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/reflex-training/quick-dodge', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/reflex-training/reaction-chain', category: 'physical', priority: 0.9 },
  { path: '/drills/physical/reflex-training/visual-rhythm-intercept', category: 'physical', priority: 0.9 },
  { path: '/drills/reaction-speed/barrier-sequence-pursuit', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/fps-tracking-trainer', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/market-doors-pursuit', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/reaction-simulator', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/reaction-time-test', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/reactive-strafe-pursuit', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/reflex-training-drill', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/saccadic-gallery', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/saccadic-snap', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/slide-dash-acceleration', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/stop-and-go-dash', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/reaction-speed/visual-tracking-speed-test', category: 'reaction-speed', priority: 0.85 },
  { path: '/drills/visual/depth-perception/distance-judgment', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/peripheral-vision/peripheral-flash', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/peripheral-vision/wide-field', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/reaction-speed/go/no-go', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/reaction-speed/light-reaction', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/reaction-speed/sound-reaction', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/tracking-accuracy/moving-target', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/tracking-accuracy/multiple-targets', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/tracking-accuracy/pursuit-tracker', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/visual-recognition/difference-spotter', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/visual-recognition/entropic-grid', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/visual-recognition/rapid-object-id', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/visual-recognition/rhythm-anomaly', category: 'visual', priority: 0.85 },
  { path: '/drills/visual/visual-recognition/visual-search', category: 'visual', priority: 0.85 },
  { path: '/drills/visual-tracking/barrier-sequence-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/circular-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/constant-slow-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/directional-chaos-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/dynamic-evasion-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/ghosting-suppress-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/infinity-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/market-doors-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/momentum-teleport-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/peripheral-ping-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/predictive-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/reaction-simulator', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/reactive-strafe-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/saccadic-gallery', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/saccadic-snap', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/sine-wave-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/slide-dash-acceleration', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/slow-precision-tracking', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/spatial-shift-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/split-screen-tracking', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/staircase-step', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/stop-and-go-dash', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/strobe-prediction-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/triangular-pursuit', category: 'visual-tracking', priority: 0.85 },
  { path: '/drills/visual-tracking/zig-zag-path-pursuit', category: 'visual-tracking', priority: 0.85 },
];

export default async function sitemap() {
  const today = new Date().toISOString().split('T')[0];
  
  const categoryEntries = categoryPages.map((page) => ({
    url: `${BASE_URL}${page.path}`,
    lastModified: today,
    changeFrequency: page.changefreq,
    priority: page.priority,
  }));
  
  const drillEntries = drillRoutes.map((drill) => ({
    url: `${BASE_URL}${drill.path}`,
    lastModified: today,
    changeFrequency: 'weekly',
    priority: drill.priority,
  }));
  
  return [...categoryEntries, ...drillEntries];
}
