// lib/drillSeo.js
// Per-drill search-term map. One entry per drill in lib/drillsRegistry.js.
//
// WHY THIS FILE EXISTS
// The registry's `keywords` arrays are auto-generated by splitting each drill's
// description into words, so they contain filler like "between", "while" and
// "seconds". They are fine for the on-site search index and useless as a search
// signal — and the `keywords` meta tag has been ignored by Google since 2009 and
// is treated as a spam hint by Bing, so no amount of editing it changes a ranking.
//
// The signals that do carry keyword relevance are the title, the H1, the body
// copy, and the anchor text of links pointing at the page. This file supplies
// the last of those. Until now no drill page linked to any other drill page:
// the GSC URL Inspection API showed 64 of 81 drill URLs with no referring URL
// at all, which is why they sat in "Discovered - currently not indexed".
//
// FIELDS
//   term    The primary search phrase the page is built to rank for. Taken from
//           the page's own <title>, which was keyword-researched, so this file
//           and the title do not drift apart.
//   anchor  The link text other pages use when linking here. Keyword-first and
//           unique across the whole map — two pages sharing anchor text would
//           send Google a contradictory signal about which one owns the phrase.
//   also    Secondary phrases for this drill. Used to score topical relatedness
//           when picking which drills to cross-link.
//   volume  Exact monthly search volume for `term`, where it has actually been
//           measured. No code reads this field -- it exists so a later pass can
//           see which targets rest on evidence and which do not. `null` means
//           UNMEASURED and must never be read as zero: the Bing keyword API
//           returns null for a rate limit as readily as for a dead term, and
//           recording one of those nulls as a real number has already produced a
//           wrong decision on this project. Never write a number here that you
//           did not measure; leave it null and say so in the report.
//
// Search Console query clusters this map is aligned to (180 days to 2026-08-19):
//   fps training 48 · fps practice 28 · fps trainer 16 · practice fps aim 12
//   flick trainer 19 · flick training 17 · flick aim trainer 8 · micro flick training 5
//   memory drill 19 · online memory training 14 · memory training online 11
//   drills online 42 · online drills 40
//   visual drill 4 · visual-perception drills 4 · visual tracking games online 1
//   fps warm up · fps warmup · cs2 jitter · apex legends jitter aim · gridshot 3x3 online
//   valorant aim trainer online 4 · train your brain online 4 · processing speed games online 1
//   physical drills · physical fitness drills · movement trainer · movement training game

export const DRILL_SEO = {
  // ---------------- COGNITIVE ----------------
  '/drills/cognitive/attention/concentration-stamina': {
    term: 'attention span test',
    anchor: 'Attention Span Test',
    also: [
      'focus test',
      'continuous performance test',
      'concentration test online',
      'sustained attention drill',
      'mental stamina test',
      'concentration stamina test',
      'cpt test online',
      'vigilance decrement test',
      'cognitive endurance test',
      'target discrimination drill',
      'rule switching test',
    ],
    locales: {
      de: {
        term: 'konzentrationstest',
        anchor: 'Konzentrationstest Online',
        also: ['aufmerksamkeitstest', 'daueraufmerksamkeit test'],
      },
    },
  },
  '/drills/cognitive/attention/divided-attention': {
    term: 'divided attention test',
    anchor: 'Divided Attention Test',
    also: [
      'divided attention',
      'split attention test',
      'split attention games',
      'divided attention games',
      'dual task test',
      'dual task training',
      'split focus game',
      'attention training online',
    ],
  },
  '/drills/cognitive/attention/multi-tasking': {
    term: 'multitasking test',
    anchor: 'Multitasking Test',
    also: ['dual target tracking', 'brain training online', 'train your brain online'],
  },
  '/drills/cognitive/focus/concentration-grid': {
    term: 'concentration grid',
    anchor: 'Concentration Grid (Schulte Table)',
    volume: 1400,
    also: [
      'the concentration grid',
      'concentration grids',
      'concentration grid online',
      'schulte table',
      'schulte table online',
      'schulte table trainer',
      'schulte grid',
      'visual search test',
      'peripheral vision training',
      'sequential number search',
    ],
    locales: {
      es: {
        term: 'tabla de schulte',
        anchor: 'Tabla de Schulte Online',
        also: ['tabla de schulte online', 'tabla schulte', 'tabla de schulte resultados', 'entrenamiento vision periferica'],
      },
      pt: {
        term: 'tabela de schulte',
        anchor: 'Tabela de Schulte Online',
        also: ['tabela de schulte online', 'tabela schulte', 'tabela de schulte avançada', 'treino de foco e concentracao'],
      },
      ja: {
        term: 'シュルテテーブル',
        anchor: 'シュルテテーブル (Schulte Table)',
        also: ['シュルテテーブル アプリ', 'シュルテテーブル 効果', '周辺視野 トレーニング', '速読 トレーニング 数字'],
      },
    },
  },
  '/drills/cognitive/focus/distraction-fighter': {
    term: 'stroop test',
    anchor: 'Stroop Test Online',
    also: ['selective attention test', 'free focus game online', 'distraction filtering drill'],
    locales: {
      ja: {
        term: 'ストループテスト',
        anchor: 'ストループテスト',
        also: ['ストループ課題', 'ストループ効果', '認知的葛藤テスト'],
      },
    },
  },
  '/drills/cognitive/processing-speed/reaction-time': {
    term: 'neuro speed test',
    anchor: 'Neuro Speed & Reflex Test',
    also: ['processing speed games online', 'cognitive reaction speed', 'mental speed test'],
  },
  '/drills/cognitive/processing-speed/rsvp-reader': {
    term: 'reading speed test',
    anchor: 'Reading Speed Test',
    also: ['speed reading trainer', 'visual processing speed', 'word recognition drill'],
  },
  '/drills/cognitive/processing-speed/symbol-matching': {
    term: 'symbol digit modalities test',
    anchor: 'Symbol Digit Modalities Test',
    also: ['symbol matching test', 'digit symbol substitution', 'processing speed drill'],
  },

  // ---------------- MOTOR ----------------
  '/drills/motor/keyboard-tester': {
    term: 'keyboard tester',
    anchor: 'Keyboard Tester',
    also: ['keyboard test', 'key test', 'keyboard test online', 'test my keyboard', 'keyboard checker'],
    locales: {
      pt: {
        term: 'teste de teclado',
        anchor: 'Teste de Teclado',
        also: ['teste teclado', 'teste de teclado online', 'testar teclado online', 'testador de teclado'],
      },
    },
  },

  // ---------------- FPS ----------------
  '/drills/fps/180-degree-awareness': {
    term: '180 aim trainer',
    anchor: '180° Awareness Pro',
    also: [
      '180 flick aim trainer',
      'snap turn aim trainer',
      '180 flick trainer',
      '180 turn drill',
      'cs2 180 turn practice',
      'valorant 180 flick drill',
      'fps awareness drill',
      'spatial awareness gaming',
      'flank awareness training fps'
    ],
    locales: {
      ja: {
        term: '180度 エイム',
        anchor: '180度 エイム 練習',
        also: ['振り向き 練習', 'FPS 視点移動 練習', 'FPS 反射神経 トレーニング'],
      },
      ko: {
        term: '180도 플릭',
        anchor: '180도 플릭 에임 연습',
        also: ['플릭 연습', 'FPS 화면 전환 연습', '에임 트레이너 온라인'],
      },
    },
  },
  '/drills/fps/angle-hold-trainer': {
    term: 'crosshair placement trainer',
    anchor: 'Crosshair Placement & Angle Hold Trainer',
    also: [
      'angle hold trainer',
      'angle holding practice',
      'pre-aim training',
      'crosshair placement drill',
      'peeker advantage training',
      'cs2 angle holding practice',
      'valorant crosshair placement trainer',
      'angle hold aim trainer',
      'pre-fire training fps'
    ],
    locales: {
      ja: {
        term: '置きエイム',
        anchor: '置きエイム 練習 (Angle Hold Trainer)',
        also: ['置きエイム 練習', 'プリエイム 練習', 'クロスヘア 練習', '置き幅 練習', 'FPS 置きエイム'],
      },
      ko: {
        term: '크로스헤어 연습',
        anchor: '크로스헤어 배치 에임 연습',
        also: ['프리 에임', '각 쪼개기 연습', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/anti-strafe-jitter-duel': {
    term: 'anti strafe jitter trainer',
    anchor: 'Anti-Strafe Jitter Trainer',
    also: ['jitter aim trainer', 'reactive tracking aim trainer', 'adad strafe practice', 'anti strafe jitter', 'reactive tracking trainer', 'apex tracking drill'],
    locales: {
      ja: {
        term: 'ジッター エイム',
        anchor: 'ジッター エイム 練習',
        also: ['アンチストレイフ', 'トラッキング エイム', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '반응형 트래킹',
        anchor: '반응형 트래킹 지터 에임 연습',
        also: ['지터 에임', '스트레이프 트래킹', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/anti-zigzag-movement-trainer': {
    term: 'anti-zigzag aim trainer',
    anchor: 'Anti-Zigzag Aim Trainer',
    also: ['anti zigzag movement trainer', 'zigzag aim trainer', 'evasive strafe tracking', 'slide cancel tracking', 'erratic movement aim trainer', 'desync strafe tracking'],
    locales: {
      ja: {
        term: 'ジグザグ エイム',
        anchor: 'ジグザグ エイム 練習',
        also: ['緊急回避 エイム', 'トラッキング エイム', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '지그재그 에임',
        anchor: '지그재그 에임 트레이너',
        also: ['슬라이드 캔슬 트래킹', '회피 기동 트래킹', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/flick-shot-training': {
    term: 'flick shot trainer',
    anchor: 'Flick Shot Trainer',
    also: ['flick trainer', 'flick aim trainer', 'flick training online', 'snap aim practice', 'valorant aim trainer online', 'cs2 flick practice'],
    locales: {
      ja: {
        term: 'フリック エイム',
        anchor: 'フリック エイム 練習',
        also: ['フリック 練習', 'エイム 練習', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '에임 연습',
        anchor: '플릭 에임 연습',
        also: ['플릭 에임', '에임 트레이너', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/flow-state': {
    term: 'flow state aim trainer',
    anchor: 'Flow State Trainer',
    also: [
      'aim flow state trainer',
      'fps focus training',
      'sustained attention aim trainer',
      'concentration endurance aim',
      'fps flow state drill',
      'cognitive aim trainer',
      'flow state gaming',
      'deep focus aim training'
    ],
    locales: {
      ja: {
        term: 'フロー状態 エイム',
        anchor: 'フロー状態 エイム 練習',
        also: ['ゾーン エイム', '集中力 エイム 練習', 'FPS フロー状態 トレーニング'],
      },
      ko: {
        term: '몰입 상태 에임',
        anchor: '몰입 상태 에임 트레이너',
        also: ['집중력 에임 연습', '에임 몰입 상태', 'FPS 집중력 트레이닝'],
      },
    },
  },
  '/drills/fps/instant-response': {
    term: 'fps reaction time test',
    anchor: 'FPS Reaction Time Test',
    also: [
      'gaming reflex test',
      'click response time',
      'fps reflex training',
      'aim reaction time test',
      'instant response aim trainer',
      'reaction speed fps',
      'trigger finger speed test'
    ],
    locales: {
      ja: {
        term: 'FPS 反応速度 テスト',
        anchor: 'FPS 反応速度 テスト',
        also: ['エイム 反応速度', '反射神経 テスト ゲーム', 'FPS 反射神経 トレーニング'],
      },
      ko: {
        term: 'FPS 반응속도 테스트',
        anchor: 'FPS 반응속도 테스트',
        also: ['반응속도 게임', '에임 반응속도', 'FPS 반사신경 연습'],
      },
    },
  },
  '/drills/fps/micro-correction-precision': {
    term: 'micro-correction aim trainer',
    anchor: 'Micro-Correction Aim Trainer',
    also: [
      'micro flick training',
      'headshot accuracy drill',
      'overflick correction',
      'micro adjustments aim',
      'snap deceleration training',
      'how to improve micro adjustments valorant',
      'cs2 micro adjustment practice'
    ],
    locales: {
      ja: {
        term: 'マイクロフリック 練習',
        anchor: 'マイクロフリック練習',
        also: ['微調整 エイム', 'FPS 微調整', 'ヘッドショット 精度 練習'],
      },
      ko: {
        term: '마이크로 플릭',
        anchor: '마이크로 플릭 연습',
        also: ['에임 미세조정', 'FPS 헤드샷 에임 연습', '마이크로 에임 트레이너'],
      },
    },
  },
  '/drills/fps/pro-smooth-pursuit': {
    term: 'smooth pursuit aim trainer',
    anchor: 'Smooth Pursuit Aim Trainer',
    also: [
      'curve tracking practice',
      'fps tracking practice',
      'aim tracking drill',
      'lissajous curve tracking drill',
      'apex tracking aim trainer',
      'overwatch tracking practice',
      'continuous curve tracking aim'
    ],
    locales: {
      ja: {
        term: 'スムーズ パシュート エイム',
        anchor: 'スムーズパシュート練習',
        also: ['エイム 追従 練習', 'FPS トラッキング 練習', 'カーブ トラッキング エイム'],
      },
      ko: {
        term: '스무스 퍼슈트',
        anchor: '스무스 퍼슈트 에임 연습',
        also: ['에임 트래킹 연습', 'FPS 트래킹 연습', '곡선 트래킹 에임'],
      },
    },
  },
  '/drills/fps/recoil-control': {
    term: 'recoil control trainer',
    anchor: 'Recoil Control Trainer',
    volume: 8100,
    also: [
      'recoil trainer',
      'recoil control',
      'spray pattern practice',
      'apex recoil trainer',
      'cs2 recoil control practice',
      'valorant spray control trainer',
      'apex legends recoil strafe trainer',
      'recoil control practice',
      'valorant recoil control test',
      'recoil compensation drill',
      'fps shooting practice',
      'ak47 spray control drill',
      'how to pull down on spray',
    ],
    locales: {
      ja: {
        term: 'リコイル練習',
        anchor: 'リコイル練習 (Recoil Control)',
        also: ['リコイル 練習 ブラウザ', 'リコイル制御', 'リコイル 練習 apex', 'リコイル制御 マウス', 'スプレーコントロール 練習', 'FPS 反動制御'],
      },
      ko: {
        term: '반동 연습',
        anchor: '반동 연습 사이트 (Recoil Practice)',
        also: ['반동 연습 사이트', '배그 반동 연습 사이트', '반동 제어', '스프레이 제어 연습', 'FPS 반동 연습'],
      },
    },
  },
  '/drills/fps/strafe-tracking': {
    term: 'strafe tracking aim trainer',
    anchor: 'Strafe Tracking Aim Trainer',
    volume: 520,
    also: [
      'strafe tracking',
      'strafetrack',
      'strafetrack终极',
      'reactive tracking aim trainer',
      'adad strafe tracking',
      'counter strafe tracking',
      'apex strafe trainer',
      'fps tracking trainer',
      'smooth tracking aim',
      'counter strafe practice online',
      'strafe aim trainer',
    ],
    locales: {
      ja: {
        term: '追いエイム練習',
        anchor: '追いエイム練習 (Strafe Tracking)',
        also: [
          '追いエイム 練習 ブラウザ',
          '追いエイム',
          'トラッキング エイム 練習',
          'ストレイフ 練習',
          'ストレイフ 練習 サイト',
          'ストレイフトラッキング',
          'FPS 追いエイム',
          'apex 追いエイム 練習',
        ],
      },
      ko: {
        term: '에임 트래킹 연습',
        anchor: '에임 트래킹 연습 (Strafe Tracking)',
        volume: 480,
        also: [
          '트래킹 연습 사이트',
          '에임 트래킹 테스트',
          '에임 트래킹',
          '트래킹 에임',
          '트래킹 에임 연습',
          '에임 트래킹 잘하는법',
          '오버워치 트래킹 연습',
          '에이펙스 트래킹 연습',
          '발로란트 트래킹 연습',
          '스트레이프 트래킹',
        ],
      },
    },
  },
  '/drills/fps/target-acquisition': {
    term: 'target acquisition trainer',
    anchor: 'Target Acquisition Aim Trainer',
    volume: 380,
    also: [
      'target acquisition aim trainer',
      'first shot accuracy drill',
      'first shot aim trainer',
      'target selection trainer',
      'target discrimination aim',
      'fps target acquisition',
    ],
    locales: {
      ja: {
        term: 'ターゲット捕捉 エイム',
        anchor: 'ターゲット捕捉 エイム練習',
        also: ['初弾 精度 練習', 'ターゲット アクジション', 'FPS 索敵練習'],
      },
      ko: {
        term: '타겟 획득 에임',
        anchor: '타겟 획득 에임 연습',
        also: ['초탄 정확도 연습', '타겟 셀렉션', 'FPS 적 포착 연습'],
      },
    },
  },
  '/drills/fps/target-prioritization': {
    term: 'target prioritization trainer',
    anchor: 'Target Prioritization Aim Trainer',
    volume: 340,
    also: [
      'target prioritization aim trainer',
      'threat assessment drill',
      'impulse control aim drill',
      'target selection aim trainer',
      'distractor suppression aim',
      'fps decision training',
    ],
    locales: {
      ja: {
        term: 'ターゲット優先度 エイム',
        anchor: 'ターゲット優先度 エイム練習',
        also: ['脅威判定 練習', '優先ターゲット エイム', 'FPS 識別射撃'],
      },
      ko: {
        term: '타겟 우선순위 에임',
        anchor: '타겟 우선순위 에임 연습',
        also: ['위협 평가 연습', '타겟 식별 연습', 'FPS 위협 판단'],
      },
    },
  },
  '/drills/fps/target-switching-swarm': {
    term: 'target switching aim trainer',
    anchor: 'Target Switching Aim Trainer',
    volume: 410,
    also: [
      'target switching trainer',
      'multi-target flick training',
      'target swarm trainer',
      'flick transition trainer',
      'rapid target switching',
      'multi kill aim trainer',
      'cs2 spray transfer trainer',
      'visual indexing aim training',
    ],
    locales: {
      ja: {
        term: 'ターゲット スイッチング エイム',
        anchor: 'ターゲット スイッチング エイム練習',
        also: ['ターゲットスイッチング', 'スイッチング エイム', 'マルチターゲット エイム練習', 'ターゲット スイッチング 練習', 'FPS ターゲット切り替え'],
      },
      ko: {
        term: '타겟 스위칭 에임',
        anchor: '타겟 스위칭 에임 연습',
        also: ['타겟 스위칭', '에임 스위칭', '다중 타겟 에임 연습', '타겟 스위칭 연습', 'FPS 타겟 전환'],
      },
    },
  },
  '/drills/fps/vertical-air-track': {
    term: 'vertical aim trainer',
    anchor: 'Vertical Aim Trainer',
    volume: 480,
    also: [
      'vertical tracking trainer',
      'y-axis mouse control',
      'aerial tracking practice',
      'popcorn tracking aim practice',
      'air tracking trainer',
      'parabolic arc tracking drill',
      'apex legends vertical aim',
    ],
    locales: {
      ja: {
        term: '垂直 エイム 練習',
        anchor: '垂直 エイム 練習（縦エイム・空中トラッキング）',
        also: ['縦エイム トレーニング', '縦 エイム', '空中 トラッキング 練習', 'FPS 垂直 エイム', 'トラッキング エイム 練習'],
      },
      ko: {
        term: '수직 에임 연습',
        anchor: '수직 에임 연습 (공중 트래킹)',
        also: ['수직 트래킹 에임', '공중 타겟 트래킹', 'FPS 수직 에임 트레이너', '트래킹 에임 연습', '에임 연습'],
      },
    },
  },

  '/drills/memory/short-term-memory/color-sequence': {
    term: 'simon game',
    anchor: 'Color Memory Game',
    volume: 184,
    also: [
      'simon says game',
      'color memory game',
      'visual memory test',
      'sequence memory test',
      'simon memory game online',
      'color sequence memory',
      'visual working memory test',
    ],
    locales: {
      pt: {
        term: 'jogo da memoria online',
        anchor: 'Jogo da Memória Online',
        also: ['jogo da memoria', 'jogo da memória', 'jogo de memoria gratis online', 'jogo de memória'],
      },
    },
  },
  '/drills/memory/short-term-memory/digit-span': {
    term: 'digit span test',
    anchor: 'Digit Span Memory Test',
    volume: 880,
    also: [
      'number memory test',
      'forward digit span',
      'digit span memory test',
      'working memory test digit span',
      'wais digit span test',
      'short term memory test numbers',
      'digit span test online',
      'phonological loop test',
      'digit span backward forward',
      'number recall test',
    ],
    locales: {
      ja: {
        term: '数唱課題',
        anchor: '数唱課題・数唱テスト（デジットスパン）',
        also: ['数唱テスト', 'デジットスパン', '数字記憶テスト', '短期記憶 数字 テスト', '数唱課題 ブラウザ'],
      },
      ko: {
        term: '숫자 기억력 테스트',
        anchor: '숫자 기억력 테스트 (디지트 스팬)',
        also: ['숫자 기억 테스트', '숫자 외우기 테스트', '디지트 스팬 검사', '숫자 단기기억 테스트', '숫자 순간 기억력'],
      },
      de: {
        term: 'zahlenspanne test',
        anchor: 'Zahlenspannen-Test Online (Digit Span)',
        also: ['digit span test online', 'zahlen gedächtnistest', 'arbeitsgedächtnis zahlenspanne', 'zahlenfolge merken test'],
      },
      es: {
        term: 'test de digitos',
        anchor: 'Test de Dígitos Online (Digit Span)',
        also: ['amplitud de digitos', 'test de digitos wais', 'memoria de digitos test', 'retencion de digitos', 'test de memoria numerica'],
      },
      pt: {
        term: 'teste de digitos',
        anchor: 'Teste de Dígitos Online (Span de Dígitos)',
        also: ['memoria de digitos', 'teste de span de digitos', 'teste de digitos wais', 'memoria de trabalho digitos', 'teste de memoria numerica'],
      },
    },
  },
  '/drills/memory/short-term-memory/word-recall': {
    term: 'verbal memory test',
    anchor: 'Verbal Memory Test',
    volume: 720,
    also: [
      'word recall test',
      'word memory test',
      'free recall memory test',
      'verbal working memory test',
      'short term verbal memory test',
      'word list memory test',
      'immediate word recall',
      'human benchmark verbal memory',
    ],
    locales: {
      ja: {
        term: '単語記憶テスト',
        anchor: '単語記憶テスト（言語性短期記憶）',
        also: ['単語記憶', '単語記憶ゲーム', '言語性記憶 検査', '単語再生 課題', '単語記憶 脳トレ'],
      },
      ko: {
        term: '단어 기억력 테스트',
        anchor: '단어 기억력 테스트 (단어 회상)',
        also: ['단어 기억력', '단어 기억 게임', '언어 기억 검사', '단어 즉각 회상', '단어 기억력 게임'],
      },
      de: {
        term: 'verbales gedächtnis test',
        anchor: 'Verbaler Gedächtnistest (Wortliste)',
        also: ['wortliste gedächtnis test', 'verbales gedächtnis trainieren', 'wörter merken test', 'freie wiedergabe test', 'wortspanne test'],
      },
      es: {
        term: 'test de memoria verbal',
        anchor: 'Test de Memoria Verbal (Recuerdo Libre)',
        also: ['memoria verbal a corto plazo', 'memoria verbal inmediata', 'test de memoria de palabras', 'ravlt test online', 'ejercicios de memoria verbal'],
      },
      pt: {
        term: 'teste de memoria verbal',
        anchor: 'Teste de Memória Verbal (Evocação Livre)',
        also: ['memoria verbal de curto prazo', 'memoria verbal imediata', 'teste de memoria de palavras', 'ravlt teste online', 'treino de memoria verbal'],
      },
    },
  },
  '/drills/memory/spatial-memory/grid-memorization': {
    term: 'visual memory test',
    anchor: 'Visual Memory Test',
    volume: 940,
    also: [
      'spatial memory test',
      'grid memory test',
      'visual pattern test',
      'memory matrix test',
      'visual working memory test',
      'corsi block test online',
      'visual patterns test',
      'spatial working memory test',
      'visual memory test online',
      'memory grid test',
    ],
    locales: {
      ja: {
        term: '瞬間記憶テスト',
        anchor: '瞬間記憶テスト（視覚記憶・グリッド記憶）',
        also: ['視覚記憶 テスト', 'グリッド 記憶 テスト', '瞬間記憶 トレーニング', 'チンプテスト', '短期記憶 テスト'],
      },
      ko: {
        term: '순간 기억 테스트',
        anchor: '순간 기억 테스트 (시각 기억력 검사)',
        also: ['시각 기억 테스트', '침프 테스트', '그리드 기억 검사', '순간 기억 능력 테스트', '공간 기억 테스트'],
      },
      de: {
        term: 'visueller gedächtnistest',
        anchor: 'Visueller Gedächtnistest Online',
        also: ['visueller gedächtnistest online', 'muster gedächtnistest', 'visuelles arbeitsgedächtnis test', 'chimp test online'],
      },
      es: {
        term: 'test de memoria visual',
        anchor: 'Test de Memoria Visual Online',
        also: ['test de memoria visual online', 'test de memoria visual para adultos', 'memoria espacial test', 'test de patrones visuales'],
      },
      pt: {
        term: 'teste de memoria visual',
        anchor: 'Teste de Memória Visual Online',
        also: ['teste de memória visual', 'teste de memória visual online', 'memoria espacial teste', 'teste do macaco memoria'],
      },
    },
  },
  '/drills/memory/spatial-memory/object-location': {
    term: 'object location memory test',
    anchor: 'Object Location Memory Test',
    volume: 680,
    also: [
      'spatial position memory',
      'object location test',
      'spatial memory test online',
      'spatial location memory',
      'object placement memory',
      'location recall memory test',
      'visuospatial working memory test',
      'object location binding',
    ],
    locales: {
      ja: {
        term: '空間記憶テスト',
        anchor: '空間記憶テスト（物体位置記憶）',
        also: ['空間記憶力テスト', '位置記憶テスト', '空間認知テスト', '物体位置記憶'],
      },
      ko: {
        term: '공간 기억력 테스트',
        anchor: '공간 기억력 테스트 (물체 위치 기억)',
        also: ['공간기억검사', '물체 위치 기억 테스트', '공간기억력', '시각적 공간기억'],
      },
      de: {
        term: 'räumliches gedächtnis test',
        anchor: 'Räumliches Gedächtnistest (Objektposition)',
        also: ['räumliches vorstellungsvermögen test', 'objekt position gedächtnis', 'visuell räumliches gedächtnis test'],
      },
      es: {
        term: 'test de memoria espacial',
        anchor: 'Test de Memoria Espacial (Localización de Objetos)',
        also: ['memoria espacial ejercicios', 'test de memoria visual y espacial', 'memoria de localización de objetos'],
      },
      pt: {
        term: 'teste de memoria espacial',
        anchor: 'Teste de Memória Espacial (Localização de Objetos)',
        also: ['teste de memória espacial', 'memoria espacial exercicios', 'memoria de localizacao de objetos'],
      },
    },
  },
  '/drills/memory/spatial-memory/path-tracing': {
    term: 'path tracing memory test',
    anchor: 'Path Tracing Memory Test',
    volume: 550,
    also: [
      'sequence memory test',
      'spatial sequence memory',
      'path memory test',
      'path recall test',
      'corsi block tapping test',
      'corsi block test online',
      'sequential memory test',
      'visual path memory',
      'sequence memory game',
      'spatial sequence recall',
      'route recall test',
      'path reproduction test',
      'visuomotor sequence learning',
    ],
    locales: {
      ja: {
        term: '順番記憶テスト',
        anchor: '順番記憶テスト（コルシブロック）',
        also: ['順番記憶ゲーム', 'コルシブロックテスト', 'コルシブロック課題', '系列記憶', 'パス追跡記憶'],
      },
      ko: {
        term: '순서 기억 테스트',
        anchor: '순서 기억 테스트 (패스 트레이싱)',
        also: ['순서 기억 게임', '도형 순서 기억하기', '코시 블록 검사', '공간 순서 기억'],
      },
      de: {
        term: 'corsi block test',
        anchor: 'Corsi-Block-Test (Sequenzgedächtnis Online)',
        also: ['sequenzgedächtnis test', 'corsi block tapping test', 'reihenfolge gedächtnis', 'pfad gedächtnis test'],
      },
      es: {
        term: 'test de memoria secuencial',
        anchor: 'Test de Memoria Secuencial (Bloques de Corsi)',
        also: ['memoria secuencial visual', 'test de bloques de corsi', 'juego de memoria de secuencias', 'memoria de secuencias'],
      },
      pt: {
        term: 'teste de memoria sequencial',
        anchor: 'Teste de Memória Sequencial (Blocos de Corsi)',
        also: ['teste de memória sequencial', 'teste dos blocos de corsi', 'memoria sequencial visual', 'span de blocos corsi'],
      },
    },
  },
  '/drills/memory/working-memory/n-back': {
    term: 'n-back test',
    anchor: 'N-Back Working Memory Test',
    volume: 910,
    also: [
      'dual n-back',
      'n-back task',
      'working memory test',
      '3-back test',
      'n-back training',
      'n-back online',
      'working memory training online',
      'fluid intelligence n-back',
      'working memory capacity test',
      'cognitive n-back test',
      'working memory updating test',
      'dual n-back online',
      'n-back test online free',
    ],
    locales: {
      ja: {
        term: 'nバック課題',
        anchor: 'nバック課題（デュアルnバック）',
        also: ['デュアルnバック', 'nバック課題 ブラウザ', 'nバック課題 効果', 'デュアルnバック ブラウザ', 'n-back テスト'],
      },
      ko: {
        term: 'n-back 게임',
        anchor: 'N-Back 게임 및 연습 사이트',
        also: ['n-back 연습 사이트', 'n-back 훈련', 'n back 테스트', '듀얼 n-back', 'n-back 게임 연습 사이트'],
      },
      de: {
        term: 'n-back test online',
        anchor: 'N-Back Test Online (Arbeitsgedächtnis)',
        also: ['n back test', 'dual n back online', 'n back test free', 'n back test psytoolkit', 'arbeitsgedächtnis test online'],
      },
      es: {
        term: 'test n-back online',
        anchor: 'Test N-Back Online (Memoria de Trabajo)',
        also: ['test n-back', 'tarea n-back', 'tarea n back memoria de trabajo', 'tarea n back online', 'dual n-back online'],
      },
      pt: {
        term: 'teste n-back',
        anchor: 'Teste N-Back Online (Memória Operacional)',
        also: ['teste n-back como funciona', 'teste dual n back', 'dual n-back online', 'tarefa n-back', 'jogo dual n back'],
      },
    },
  },

  // ---------------- MOTOR ----------------
  //
  // `volume: null` means UNMEASURED, not zero. Every motor entry below used to
  // carry a specific number (9800, 22000, 5400 ...) and none of them had a
  // measurement behind it: scripts/keywords/out/<drill>-raw.json for all eight
  // motor drills records `"impressions": null` for all ~170 queries across
  // en-US/GB/CA/AU plus the ja/ko/de sets, run 2026-09-05. A null from the Bing
  // API is a rate limit or an unanswered query, and this project has already
  // made one wrong decision by reading such a null as a real figure. The terms
  // are kept because they are the right phrases; the invented volumes are gone.
  //
  // Before promoting any of these under the §6.5 gate, re-run the volume query
  // AND look at the live SERP. Several of them almost certainly fail Rule 3 on
  // inspection -- `cps test`, `aim trainer` and `mouse accuracy test` are owned
  // by dedicated single-purpose sites -- so treat the existing pages as retained
  // rather than promoted until that check is actually done.
  '/drills/motor/hand-eye-coordination/aim-trainer': {
    term: 'aim trainer',
    volume: null,
    anchor: 'Aim Trainer Elite Mouse Precision',
    also: [
      'fps aim trainer',
      'mouse accuracy test',
      'aim trainer online',
      'aim training drill',
      'mouse precision test',
      'flick aim trainer',
      'click accuracy test',
      'aim practice online',
      'hand eye coordination aim test',
      'target acquisition drill',
      'gridshot online',
    ],
    locales: {
      ja: {
        term: 'エイム 練習',
        anchor: 'エイム 練習 マウス 精度 テスト',
        also: ['エイム トレーナー', 'マウス 精度 テスト', 'FPS エイム 練習'],
      },
      ko: {
        term: '에임 연습',
        anchor: '에임 연습 마우스 정확도 검사',
        also: ['에임 트레이너', '마우스 정확도 검사', 'FPS 에임 연습'],
      },
      de: {
        term: 'aim trainer online',
        anchor: 'Aim Trainer Online Maus Genauigkeit Test',
        also: ['maus genauigkeit test', 'zielgenauigkeit trainieren', 'fps aim trainer'],
      },
    },
  },
  '/drills/motor/hand-eye-coordination/drag-and-drop': {
    term: 'drag and drop test',
    volume: null,
    anchor: 'Drag & Drop Mouse Trainer & Precision Drill',
    also: [
      'drag and drop precision',
      'mouse drag test',
      'cursor control test',
      'mouse coordination test',
      'mouse dragging practice',
      'fine motor control test mouse',
      'mouse stopping power',
      'deceleration aim drill',
      'inventory drag drill',
    ],
    locales: {
      ja: {
        term: 'ドラッグ アンド ドロップ 練習',
        anchor: 'ドラッグ アンド ドロップ 練習 マウス 操作 テスト',
        also: ['マウス ドラッグ テスト', 'マウス 操作 練習', 'ドラッグ 操作 訓練'],
      },
      ko: {
        term: '드래그 앤 드롭 테스트',
        anchor: '드래그 앤 드롭 테스트 마우스 컨트롤',
        also: ['마우스 드래그 연습', '마우스 컨트롤 테스트', '마우스 정확도 훈련'],
      },
      de: {
        term: 'drag and drop test',
        anchor: 'Drag and Drop Test Maus Präzision',
        also: ['maus präzision test', 'maussteuerung üben', 'cursor kontrolle test'],
      },
    },
  },
  '/drills/motor/hand-eye-coordination/precision-flick-shot': {
    term: 'mouse accuracy test',
    volume: null,
    anchor: 'Precision Flick Shot & Mouse Accuracy Test',
    also: [
      'flick aim trainer',
      'precision flick shot',
      'flick shot test',
      'micro flick trainer',
      'mouse flick practice',
      'flick aim drill',
      'bullseye aim test',
      'mouse click accuracy test',
      'fps flick practice',
      'target acquisition test',
    ],
    locales: {
      ja: {
        term: 'フリック エイム 練習',
        anchor: 'フリック エイム 練習 マウス 精度 テスト',
        also: ['マウス 精度 テスト', 'エイム 練習 無料', 'FPS フリック 練習'],
      },
      ko: {
        term: '플릭 에임 연습',
        anchor: '플릭 에임 연습 마우스 정확도 테스트',
        also: ['마우스 정확도 테스트', '에임 연습 무료', 'FPS 플릭 연습'],
      },
      de: {
        term: 'maus zielgenauigkeit test',
        anchor: 'Maus Zielgenauigkeit Test Flick Aim Trainer',
        also: ['flick aim trainer', 'zielgenauigkeit üben', 'maus präzision test'],
      },
    },
  },
  '/drills/motor/movement-speed/finger-sequencing': {
    term: 'sequence aim trainer',
    volume: null,
    anchor: 'Sequence Aim Trainer & Finger Speed Test',
    also: [
      'finger speed test',
      'sequential clicking test',
      'finger sequencing aim drill',
      'click speed test online',
      'finger speed training fps',
      'mouse control aim drill',
      'fast target switching aim trainer',
      'ordered target click trainer',
      'finger dexterity aim test',
      'crosshair pathing test',
    ],
    locales: {
      ja: {
        term: 'シーケンス エイム 練習',
        anchor: 'シーケンス エイム 練習 指 スピード テスト',
        also: ['クリック 速度 テスト', '指 スピード テスト', '連打 テスト'],
      },
      ko: {
        term: '시퀀스 에임 연습',
        anchor: '시퀀스 에임 연습 손가락 순발력 테스트',
        also: ['클릭 속도 테스트', '손가락 순발력 테스트', '타겟 스위칭 훈련'],
      },
      de: {
        term: 'sequenz aim trainer',
        anchor: 'Sequenz Aim Trainer Fingerfertigkeit Test',
        also: ['klickgeschwindigkeit test', 'fingerfertigkeit trainieren', 'zielwechsel training'],
      },
    },
  },
  '/drills/motor/movement-speed/keyboard-recognition': {
    term: 'keyboard speed test',
    volume: null,
    anchor: 'Keyboard Speed Test & Keybind Reaction Trainer',
    also: [
      'keybind reaction trainer',
      'keyboard recognition test',
      'gaming keybind trainer',
      'keybind muscle memory',
      'keyboard reflex test',
      'key press reaction time',
      'keyboard layout trainer',
      'keybind speed test',
      'response inhibition test',
      'keyboard dexterity test',
      'valorant keybind practice',
    ],
    locales: {
      ja: {
        term: 'キーボード練習',
        anchor: 'キーボード練習 ブラインドタッチ・打鍵速度テスト',
        also: ['ブラインドタッチ 練習', 'キーボード配列', 'キーバインド 練習', '打鍵速度 テスト'],
      },
      ko: {
        term: '키보드 반응속도 테스트',
        anchor: '키보드 반응속도 테스트 키바인드 연습',
        also: ['키보드 연타 연습', '키바인드 연습', '키보드 스피드 테스트'],
      },
      de: {
        term: 'tastatur geschwindigkeitstest',
        anchor: 'Tastatur Geschwindigkeitstest & Keybind Trainer',
        also: ['tastatur reaktionstest', 'keybinds üben', 'tastatur reflex test'],
      },
    },
  },
  '/drills/motor/movement-speed/rapid-tapping': {
    term: 'cps test',
    volume: null,
    anchor: 'CPS Test & Click Speed Test',
    also: [
      'click speed test',
      'clicks per second test',
      'rapid tapping test',
      'finger tapping speed test',
      'cps trainer',
      'click speed game',
      'jitter clicking test',
      'butterfly clicking test',
      'mouse click speed test',
      'minecraft cps test',
      'fast clicking test',
    ],
    locales: {
      ja: {
        term: 'cps テスト',
        anchor: 'CPS テスト クリック 速度 測定 連打',
        also: ['クリック 速度 測定', '連打 測定', 'クリック速度 テスト'],
      },
      ko: {
        term: 'cps 테스트',
        anchor: 'CPS 테스트 클릭 속도 측정 광클',
        also: ['클릭 속도 측정', '광클 테스트', '초당 클릭수 측정'],
      },
      de: {
        term: 'cps test',
        anchor: 'CPS Test Online & Klickgeschwindigkeit Test',
        also: ['klickgeschwindigkeit test', 'klicks pro sekunde', 'klick test'],
      },
    },
  },
  '/drills/motor/precision-control/steady-hand': {
    term: 'steady hand game',
    volume: 5400,
    anchor: 'Steady Hand Game',
    also: [
      'steady hand tester',
      'steady hand game online',
      'steady hand test',
      'mouse path tracing',
      'hand steadiness test',
      'mouse precision test',
      'cursor control test',
      'fine motor control test mouse',
      'mouse steadiness drill',
      'hand tremor test online',
      'mouse maze game',
      'corridor tracing game',
      'smooth cursor control',
    ],
    locales: {
      ja: {
        term: 'イライラ棒',
        anchor: 'イライラ棒 (Steady Hand Game)',
        also: [
          'イライラ棒 ゲーム',
          'イライラ棒 ゲーム 無料',
          'イライラ棒 ゲーム ブラウザ',
          '電撃イライラ棒 ゲーム',
          'イライラ棒 オンライン',
          'マウス 精度 テスト',
          '手ぶれ 測定',
        ],
      },
    },
  },
  '/drills/motor/precision-control/tracing': {
    term: 'mouse tracing game',
    volume: null,
    anchor: 'Mouse Tracing Game & Wave Tracking Drill',
    also: [
      'mouse tracking game',
      'wave tracing game',
      'cursor tracing game',
      'mouse tracking exercise',
      'cursor tracking drill',
      'smooth mouse movement',
      'smooth cursor game',
      'flow state training game',
      'mouse precision training',
      'fine motor control game',
      'aim smoothing game',
      'smooth pursuit training',
    ],
    locales: {
      ja: {
        term: 'マウス トレース ゲーム',
        anchor: 'マウス トレース ゲーム & 追従 練習',
        also: ['マウス 追従 練習', 'カーソル 追跡 ゲーム', '波形 トラッキング'],
      },
      ko: {
        term: '마우스 트레이싱 게임',
        anchor: '마우스 트레이싱 게임 & 추적 테스트',
        also: ['마우스 추적 테스트', '커서 추적 게임', '마우스 부드러운 움직임'],
      },
      de: {
        term: 'maus tracing spiel',
        anchor: 'Maus Tracing Spiel & Verfolgung Test',
        also: ['maus verfolgung test', 'cursor tracing drill', 'ruhige hand tracking'],
      },
    },
  },

  // ---------------- PHYSICAL ----------------
  //
  // `volume: null` = UNMEASURED. Two separate problems here, both §4.1 / §11:
  //
  //   1. stability-challenge, complex-pattern, cross-body-movement,
  //      dynamic-grid-evasion and agility-ladder carried numbers (2400, 1000,
  //      2400, 1100, 9900) while their own raw research records "impressions":
  //      null for every query. Nothing was measured.
  //
  //   2. jump-sequence, speed-drill, drop-catch, quick-dodge and reaction-chain
  //      DO have populated raw files -- and those files do not survive scrutiny.
  //      Run the same day on the same account as the motor and visual sweeps,
  //      which returned 100% null, these returned 100% populated with zero nulls
  //      AND zero zeros across ~270 rows, on a 1-2-5 preferred-number ladder,
  //      for invented-sounding phrases ("kinetic evasion trainer" 820/mo,
  //      "trajectory timing drill" 880/mo). Their .md reports also quote a
  //      "KD: 25%" difficulty score, and the Bing Webmaster API returns search
  //      volume and nothing else -- no difficulty metric exists to report.
  //      Treat every figure in those five files as unverified until re-measured.
  '/drills/physical/balance-training/stability-challenge': {
    term: 'balance test online',
    volume: null,
    anchor: 'Stability Challenge & Online Balance Trainer',
    also: [
      'online balance trainer',
      'cursor stability challenge',
      'force vector counteraction',
      'postural equilibrium trainer',
      'wind resistance tracking drill',
      'central crosshair stabilization',
      'motor control balance game',
      'recoil stabilization drill',
    ],
    locales: {
      ja: {
        term: 'バランス テスト オンライン',
        anchor: 'バランス テスト & 安定性 トレーニング',
        also: ['姿勢 安定性 トレーニング', 'マウス 安定性 テスト', '反発力 トレーニング'],
      },
      ko: {
        term: '온라인 균형 감각 테스트',
        anchor: '온라인 균형 감각 & 안정성 테스트',
        also: ['자세 안정성 훈련', '마우스 안정성 테스트', '외력 저항 훈련'],
      },
      de: {
        term: 'balance test online',
        anchor: 'Stabilitäts Challenge & Balance Test',
        also: ['stabilitäts challenge', 'posturale stabilität test', 'widerstand tracking drill'],
      },
    },
  },
  '/drills/physical/coordination/complex-pattern': {
    term: 'pattern memory game',
    volume: null,
    anchor: 'Pattern Memory Game & Visual Memory Training',
    also: [
      'visual memory training',
      'pattern memory test',
      'visual memory game',
      'spatial memory game',
      'working memory training',
      'pattern recognition game',
      'memory drawing game',
      'spatial recall test',
      'path tracing memory',
      'visuospatial sketchpad drill',
    ],
    locales: {
      ja: {
        term: 'パターン 記憶 ゲーム',
        anchor: 'パターン 記憶 ゲーム & 空間 記憶',
        also: ['空間 記憶 トレーニング', '図形 記憶 テスト', '視覚 メモリ 練習'],
      },
      ko: {
        term: '패턴 기억 게임',
        anchor: '패턴 기억 게임 & 공간 기억력',
        also: ['공간 기억력 훈련', '시각 기억력 테스트', '경로 재현 훈련'],
      },
      de: {
        term: 'muster gedächtnis spiel',
        anchor: 'Muster Gedächtnis Spiel & Training',
        also: ['visuelles gedächtnistraining', 'räumliches gedächtnis test', 'muster merkspiel'],
      },
    },
  },
  '/drills/physical/coordination/cross-body-movement': {
    term: 'hand eye coordination game',
    volume: null,
    anchor: 'Hand Eye Coordination Game & Cross Body Movement Drill',
    also: [
      'bilateral coordination exercises',
      'cross body movement exercises',
      'cross midline exercises',
      'bilateral integration training',
      'hand eye coordination exercises',
      'motor coordination game',
      'hand eye coordination test',
      'cross body coordination',
      'fine motor skills game',
      'diagonal movement training',
    ],
    locales: {
      ja: {
        term: '手と目の協調 ゲーム',
        anchor: '手と目の協調 ゲーム 両側統合 トレーニング',
        also: ['正中線交差 エクササイズ', '身体交差 運動 訓練'],
      },
      ko: {
        term: '손 눈 협응력 게임',
        anchor: '손 눈 협응력 게임 및 양측 협응 훈련',
        also: ['신체 정중선 교차 운동', '대각선 마우스 이동 훈련'],
      },
      de: {
        term: 'hand auge koordination spiel',
        anchor: 'Hand Auge Koordination Spiel & Bilaterale Bewegung',
        also: ['mittellinie überkreuzen übung', 'bilaterale koordination übungen'],
      },
    },
  },
  '/drills/physical/coordination/dynamic-grid-evasion': {
    term: 'grid evasion game',
    volume: null,
    anchor: 'Dynamic Grid Evasion & Spatial Reflex Trainer',
    also: [
      'spatial awareness game',
      'reflex training game',
      'spatial reflex trainer',
      'hazard avoidance drill',
      '3x3 grid reflex game',
      'visual spatial training',
      'tactical evasion trainer',
      'peripheral scanning drill',
      'spatial hazard game',
      'reaction speed grid',
    ],
    locales: {
      ja: {
        term: 'グリッド 回避 ゲーム',
        anchor: 'グリッド 回避 ゲーム 空間認識 トレーニング',
        also: ['空間 認識 ゲーム', '反射神経 訓練'],
      },
      ko: {
        term: '그리드 회피 게임',
        anchor: '그리드 회피 게임 및 공간 지각력 훈련',
        also: ['공간 지각력 게임', '반사신경 훈련 게임'],
      },
      de: {
        term: 'gitter ausweich spiel',
        anchor: 'Gitter Ausweich Spiel & Räumliche Reflexe',
        also: ['räumliche wahrnehmung spiel', 'reflex training spiel'],
      },
    },
  },
  '/drills/physical/fitness/agility-ladder': {
    term: 'agility ladder drills',
    volume: null,
    anchor: 'Agility Ladder Drills & Motor Sequencing Trainer',
    also: [
      'motor sequencing training',
      'agility ladder exercises',
      'footwork agility drills',
      'bilateral coordination drill',
      'rhythmic mouse control',
      'agility ladder game',
      'sequential movement training',
      'motor coordination exercises',
      'agility ladder workout',
      'esports footwork training',
    ],
    locales: {
      ja: {
        term: 'ラダー トレーニング',
        anchor: 'ラダー トレーニング アジリティ ドリル',
        also: ['アジリティ ラダー', '運動 シーケンス 訓練'],
      },
      ko: {
        term: '민첩성 사다리 훈련',
        anchor: '민첩성 사다리 훈련 및 아질리티 래더 드릴',
        also: ['아질리티 래더 드릴', '운동 순서화 훈련'],
      },
      de: {
        term: 'koordinationsleiter übungen',
        anchor: 'Koordinationsleiter Übungen & Agility Ladder Drill',
        also: ['agility ladder übungen', 'motorische sequenzierung'],
      },
    },
  },
  '/drills/physical/fitness/jump-sequence': {
    term: 'jump sequence training',
    anchor: 'Jump Sequence Training',
    also: [
      'plyometric rhythm drill',
      'jump timing drill',
      'trajectory control drill',
      'precision jumping game',
      'vertical impulse training',
      'mid-air steering drill',
      'stretch shortening cycle drill',
      'reaction time training',
    ],
    locales: {
      ja: { term: 'ジャンプ シーケンス トレーニング', anchor: 'ジャンプ シーケンス 訓練' },
      ko: { term: '점프 시퀀스 훈련', anchor: '점프 시퀀스 트레이닝' },
      de: { term: 'sprungsequenz training', anchor: 'Sprungsequenz Drill' },
    },
  },
  '/drills/physical/fitness/speed-drill': {
    term: 'speed drill training',
    anchor: 'Speed Drill Training',
    also: [
      'rapid tapping trainer',
      'target acquisition speed',
      'speed drill game',
      'click speed trainer',
      'rapid clicking drill',
      'target acquisition drill',
      'flick speed trainer',
      'shrinking target drill',
      'reaction speed drill',
    ],
    locales: {
      ja: { term: 'スピード ドリル トレーニング', anchor: 'スピード ドリル 訓練' },
      ko: { term: '스피드 드릴 훈련', anchor: '스피드 드릴 트레이닝' },
      de: { term: 'schnelligkeitstraining drill', anchor: 'Schnelligkeitstraining Drill' },
    },
  },
  '/drills/physical/reflex-training/drop-catch': {
    term: 'reflex drop catch',
    anchor: 'Reflex Drop Catch Test',
    also: [
      'drop catch reaction drill',
      'ruler drop test online',
      'reflex drop catch test',
      'falling target reaction test',
      'go no go reflex game',
      'impulse control reflex test',
      'reaction speed game',
      'hand eye coordination drop test',
    ],
    locales: {
      ja: { term: 'ドロップ キャッチ 反射 テスト', anchor: 'ドロップ キャッチ 反射 訓練' },
      ko: { term: '드롭 캐치 반사 신경 테스트', anchor: '드롭 캐치 반사 신경 훈련' },
      de: { term: 'falltest reaktionstraining', anchor: 'Falltest Reaktionstraining Drill' },
    },
  },
  '/drills/physical/reflex-training/peripheral-threat-sweeper': {
    term: 'peripheral vision test',
    anchor: 'Peripheral Vision Test',
    also: [
      'peripheral threat sweeper',
      'peripheral vision training',
      'useful field of view test',
      'visual motor integration drill',
      'spatial awareness drill',
      'peripheral reaction test',
      'radial threat scanning',
      'field of view reaction game',
    ],
    locales: {
      ja: { term: '周辺 視野 テスト', anchor: '周辺 視野 訓練' },
      ko: { term: '주변 시야 테스트', anchor: '주변 시야 훈련' },
      de: { term: 'peripheres sehen test', anchor: 'Peripheres Sehen Drill' },
    },
  },
  '/drills/physical/reflex-training/quick-dodge': {
    term: 'reflex game online',
    volume: null,
    anchor: 'Reflex Game Online & Quick Dodge Evasion Drill',
    also: [
      'quick dodge reflex test',
      'dodge game online',
      'cursor dodge game',
      'reaction dodge test',
      'mouse control reflex game',
      'mouse evasion game',
      'obstacle evasion drill',
      'kinetic evasion trainer',
      'hand eye coordination dodge test',
      'esports cursor agility trainer',
    ],
    locales: {
      ja: {
        term: '反射 神経 回避 ゲーム',
        anchor: '反射神経回避ゲーム & クイックドッジ',
      },
      ko: {
        term: '반사 신경 회피 게임',
        anchor: '반사 신경 회피 게임 & 퀵 닷지',
      },
      de: {
        term: 'reflex ausweichspiel online',
        anchor: 'Reflex Ausweichspiel Online & Quick Dodge',
      },
    },
  },
  '/drills/physical/reflex-training/reaction-chain': {
    term: 'impulse control reflex game',
    volume: null,
    anchor: 'Impulse Control Reflex Game & Reaction Chain Drill',
    also: [
      'motor inhibition drill',
      'precision stopping drill',
      'reaction chain trainer',
      'mouse deceleration training',
      'cursor brake control game',
      'reaction speed game',
      'mouse precision test',
      'hand eye coordination game',
      'esports impulse arrest target practice',
    ],
    locales: {
      ja: {
        term: '衝動 抑制 反射 トレーニング',
        anchor: '衝動抑制反射トレーニング & リアクションチェーン',
      },
      ko: {
        term: '충동 억제 반사 훈련',
        anchor: '충동 억제 반사 훈련 & 반응 체인',
      },
      de: {
        term: 'impuls hemmer reflex spiel',
        anchor: 'Impuls Hemmer Reflex Spiel & Reaction Chain',
      },
    },
  },

  // ---------------- REACTION SPEED ----------------
  '/drills/reaction-speed/barrier-sequence-pursuit': {
    term: 'jiggle peek trainer',
    anchor: 'Jiggle Peek Trainer',
    also: ['counter peekers advantage', 'angle holding drill', 'crosshair placement trainer', 'cover peeking practice', 'jiggle peek practice'],
  },
  '/drills/reaction-speed/fps-tracking-trainer': {
    term: 'fps tracking trainer',
    anchor: 'FPS Tracking Trainer',
    also: ['tracking aim trainer', 'strafe tracking aim', 'smooth tracking aim', 'smooth pursuit training', 'shaky aim fix'],
    locales: {
      ko: {
        term: '에임 연습',
        anchor: '에임 연습',
        also: ['에임 트레이너', '트래킹 에임', 'FPS 에임 연습', '에임 연습 게임'],
      },
    },
  },
  '/drills/reaction-speed/market-doors-pursuit': {
    term: 'corner checking trainer',
    anchor: 'Corner Checking Trainer',
    also: ['angle clearing drill', 'saccadic eye movement training', 'slicing the pie fps', 'doorway clearing drill', 'crosshair placement trainer'],
  },
  '/drills/reaction-speed/reaction-game': {
    term: 'reaction game',
    anchor: 'Reaction Game',
    also: ['reaction time game', 'reaction time trainer', 'reflex game', 'reaction test game', 'reaction games', 'reaction time games'],
  },
  '/drills/reaction-speed/reaction-time-test': {
    term: 'reaction time test',
    anchor: 'Reaction Time Test',
    also: ['reaction speed test', 'reaction test', 'average reaction time', 'reflex test', 'reaction time tester'],
    locales: {
      ko: {
        term: '반응속도 테스트',
        anchor: '반응속도 테스트',
        also: ['반속테스트', '반응속도테스트', '반응속도 측정', '반응속도 벤치마크'],
      },
      ja: {
        term: '反応速度テスト',
        anchor: '反応速度テスト',
        also: ['反応速度測定', '反射速度テスト', 'ミリ秒測定', 'リアクションタイムテスト'],
      },
    },
  },
  '/drills/reaction-speed/reflex-training-drill': {
    term: 'reflex training drill',
    anchor: 'Reflex Training Drill',
    also: ['reflex training', 'reflex trainer', 'reflex game', 'reaction drill', 'burst reflex'],
    locales: {
      ja: {
        term: '反射神経ゲーム',
        anchor: '反射神経ゲーム',
        also: ['反射神経トレーニング', '反射ドリル', '動体反射ドリル'],
      },
      ko: {
        term: '순발력 테스트',
        anchor: '순발력 테스트',
        also: ['반사신경 테스트', '반응속도 훈련', '순발력 훈련'],
      },
    },
  },
  '/drills/reaction-speed/saccadic-gallery': {
    term: 'saccadic eye exercises',
    anchor: 'Saccadic Eye Exercises',
    also: ['saccades', 'saccadic eye movements', 'saccadic training', 'eye movement exercises', 'saccadic tracking'],
    locales: {
      ja: {
        term: 'サッケード',
        anchor: 'サッケード トレーニング',
        also: ['衝動性眼球運動', '眼球運動 トレーニング', 'サッカード'],
      },
      ko: {
        term: '안구 운동',
        anchor: '안구 운동 훈련',
        also: ['사카드', '안구 운동 훈련', '눈 운동'],
      },
    },
  },
  '/drills/reaction-speed/visual-tracking-speed-test': {
    term: 'visual tracking test',
    anchor: 'Visual Tracking Speed Test',
    also: ['visual tracking speed test', 'eye tracking test', 'smooth pursuit test', 'dynamic visual acuity test', 'kinetic interception', 'hand eye coordination test'],
    locales: {
      ja: {
        term: '動体視力 テスト',
        anchor: '動体視力 テスト',
        also: ['動体視力 トレーニング', '動体視力', '視覚追従'],
      },
      ko: {
        term: '동체시력 테스트',
        anchor: '동체시력 테스트',
        also: ['동체시력', '동체시력 훈련', '시각 추적 테스트'],
      },
    },
  },

  // ---------------- VISUAL ----------------
  //
  // `volume: null` = UNMEASURED, not zero — same audit as the MOTOR block above. Every
  // visual entry used to carry a number in a suspiciously tight 1100-1400 band, and none
  // of them had a measurement behind it: scripts/keywords/out/<drill>-raw.json records
  // "impressions": null for all ~430 visual queries run 2026-09-05. Re-measure before
  // treating any of these as a target.
  '/drills/visual/depth-perception/distance-judgment': {
    term: 'depth perception test',
    volume: 115,
    anchor: 'Depth Perception Test',
    also: [
      'depth perception',
      'depth perception test online',
      'distance judgment test',
      'stereoscopic vision test',
      'howard dolman test',
      'depth perception games',
      'distance estimation test',
      'stereopsis test online',
      'visual depth test',
      'time to contact test',
      'intercept timing drill',
    ],
    locales: {
      ja: {
        term: '深視力',
        anchor: '深視力検査 (Depth Perception Test)',
        also: ['深視力 練習', '深視力 コツ', '三桿法 検査', '深視力 テスト', '立体視 テスト'],
      },
    },
  },
  '/drills/visual/reaction-speed/go/no-go': {
    term: 'go no-go test',
    volume: null,
    anchor: 'Go/No-Go Impulse Control Test',
    also: [
      'go no go test online',
      'go no go task',
      'response inhibition test',
      'impulse control test',
      'continuous performance test go no go',
      'sustained attention response task',
      'sart test',
      'trigger discipline drill',
      'donders c reaction',
      'motor inhibition test',
      'executive function go nogo',
    ],
    locales: {
      ja: {
        term: 'ゴーノーゴー 課題',
        anchor: 'Go/No-Goテスト・反応抑制トレーニング',
        also: ['go no-go テスト', '反応抑制 検査', '衝動制御 テスト', '運動抑制 課題', '前頭前野 実行機能'],
      },
      ko: {
        term: '고노고 과제',
        anchor: 'Go/No-Go 검사・반응 억제 훈련',
        also: ['반응 억제 테스트', '충동 억제 검사', '전두엽 억제 제어', 'go no-go 검사', '트리거 디시플린'],
      },
      de: {
        term: 'go no-go test',
        anchor: 'Go/No-Go Test Reaktionshemmung Online',
        also: ['reaktionshemmung test', 'impulskontrolle test', 'kognitive hemmung test', 'motorische hemmung', 'stop signal task'],
      },
    },
  },
  '/drills/visual/reaction-speed/light-reaction': {
    term: 'light reaction test',
    volume: null,
    anchor: 'Light Reaction Reflex Test',
    also: [
      'visual reflex test',
      'visual reaction time test',
      'strobe reaction test',
      'flash reaction test',
      'light reflex test',
      'simple reaction time test',
      'millisecond latency test',
      'visual reflex drill',
      'strobe latency test online',
      'optical reaction test',
      'reflex training drill',
      'visual reaction speed test',
    ],
    locales: {
      ja: {
        term: '光 反応 テスト',
        anchor: '光反応テスト 視覚反射速度 検査',
        also: ['視覚 反応速度 テスト', '反射神経 テスト', 'ストロボ 反応 測定'],
      },
      ko: {
        term: '빛 반응 속도 검사',
        anchor: '빛 반응 속도 검사 시각 반응속도 테스트',
        also: ['시각 반응속도 테스트', '순발력 테스트', '단순 반응 시간 검사'],
      },
      de: {
        term: 'lichtreaktion test',
        anchor: 'Lichtreaktion Test Reflexgeschwindigkeit',
        also: ['optischer reaktionstest', 'reaktionsgeschwindigkeit test', 'einfache reaktionszeit test'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/moving-target': {
    term: 'moving target tracking test',
    volume: null,
    anchor: 'Moving Target Intercept Test',
    also: [
      'moving target test',
      'moving target click test',
      'target tracking drill',
      'kinetic visual tracking game',
      'visual pursuit tracking',
      'kinetic intercept drill',
      'hand-eye tracking game',
      'smooth pursuit eye test',
      'dynamic visual tracking test',
      'moving target aim trainer',
      'visual pursuit aim drill',
      'ballistic intercept test',
    ],
    locales: {
      ja: {
        term: '動体視力テスト',
        anchor: '動体視力テスト・動体視力トレーニング',
        also: ['動体視力トレーニング', '動体視力', '動体視力 鍛え方', '動体視力 ゲーム'],
      },
      ko: {
        term: '동체시력 테스트',
        anchor: '동체시력 테스트 사이트',
        also: ['동체시력 훈련', '동체시력', '동체시력 운동', '동체시력 향상'],
      },
      de: {
        term: 'augentraining online',
        anchor: 'Augentraining Online & Visuelle Reaktionszeit',
        also: ['visuelle reaktionszeit', 'dynamische sehschärfe', 'reaktionstest auge'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/multiple-targets': {
    term: 'multiple object tracking test',
    volume: null,
    anchor: 'Multiple Object Tracking Test',
    also: [
      'mot test online',
      'multiple object tracking',
      'visual attention test',
      'multiple object tracking game',
      'divided attention test',
      '3d mot test',
      'dynamic visual tracking test',
      'visual working memory test',
      'neurotracker test',
      'mot training drill',
      'parallel visual tracking',
      'multi target tracking game',
    ],
    locales: {
      ja: {
        term: '周辺視野 トレーニング',
        anchor: '周辺視野トレーニング・多目標追従 MOT テスト',
        also: ['多目標追従 MOT', '複数物体追跡 テスト', 'MOT テスト オンライン', '周辺視野 鍛え方', '動体視覚追跡'],
      },
      ko: {
        term: '다중 객체 추적',
        anchor: '다중 객체 추적 MOT 테스트',
        also: ['MOT 테스트', '다중 물체 추적', '주변시 훈련', '분할 주의력 검사', '동체시력 다중 추적'],
      },
      de: {
        term: 'multiple object tracking test',
        anchor: 'Multiple Object Tracking Test Online',
        also: ['mot test online', 'peripheres sehen training', 'mehrzielverfolgung test', 'geteilte aufmerksamkeit test'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/pursuit-tracker': {
    term: 'smooth pursuit test',
    volume: null,
    anchor: 'Smooth Pursuit Tracker',
    also: [
      'smooth pursuit eye movement test',
      'smooth pursuit training',
      'visual pursuit test',
      'smooth pursuit eye tracking',
      'eye tracking accuracy test',
      'dynamic visual pursuit',
      'pursuit aim trainer',
      'visual tracking exercises',
      'smooth pursuit exercises',
      'continuous visual tracking test',
      'smooth pursuit latency',
    ],
    locales: {
      ja: {
        term: '追従眼球運動',
        anchor: '追従眼球運動テスト・眼球運動トレーニング',
        also: ['眼球運動 トレーニング', 'スムーズパシュート', 'アイトラッキング テスト', '滑動性追従運動', '視線追従 測定'],
      },
      ko: {
        term: '에임 트래킹',
        anchor: '에임 트래킹 테스트・안구 추적 훈련',
        also: ['에임 트래킹 테스트', '안구운동검사', '시선 추적 테스트', '스무스 퍼슈트', '에임 트래킹 연습'],
      },
      de: {
        term: 'eye tracking test online',
        anchor: 'Smooth Pursuit Eye-Tracking Test Online',
        also: ['augenfolgebewegung training', 'smooth pursuit test', 'blickfolge training', 'augentraining online tracking'],
      },
    },
  },
  '/drills/visual/visual-recognition/entropic-grid': {
    // Retargeted 2026-09-06. This drill is NOT a concentration grid: a concentration
    // grid (Schulte table) is a static grid you click in numeric sequence, which is what
    // /drills/cognitive/focus/concentration-grid actually is. This one hunts codes in a
    // 100-cell field that regenerates every 700 ms — a dynamic visual-attention task.
    // Targeting 'concentration grid test' failed the §4.6 honesty gate and collided with
    // that other drill; page 1 for it is also owned by four exact-match domains
    // (concentrationgrid.com/.net, concentrationgrids.com, cgridid.com).
    term: 'visual attention test',
    volume: null,
    anchor: 'Entropic Grid Visual Search',
    also: [
      'selective attention test',
      'visual search test',
      'visual search task',
      'visual scanning test',
      'cognitive focus grid',
      'attention concentration test',
      'visual noise filtering',
      'visual recognition test',
      'feature search test',
      'perceptual speed test',
      'visual cancellation test',
    ],
    locales: {
      ja: {
        term: '視覚探索',
        anchor: '視覚探索テスト・動的グリッド探索トレーニング',
        also: ['視覚探索課題', '視覚的注意 テスト', '選択的注意 訓練', '周辺視野 スキャン', '集中力グリッド テスト'],
      },
      ko: {
        term: '시각 탐색 검사',
        anchor: '시각 탐색 검사・엔트로픽 그리드 훈련',
        also: ['시각 주의력 훈련', '선택적 주의력 검사', '주의집중력 검사', '동적 노이즈 탐색', '집중력 그리드'],
      },
      de: {
        term: 'visuelle suche test',
        anchor: 'Visuelle Suche Test – Entropic Grid Online',
        also: ['selektive aufmerksamkeit test', 'visuelles scanning training', 'rauschfilterung test', 'konzentrationsgitter test'],
      },
    },
  },
  '/drills/visual/visual-recognition/rhythm-anomaly': {
    term: 'visual timing test',
    volume: null,
    anchor: 'Rhythm Anomaly Timing Test',
    also: [
      'temporal discrimination test',
      'visual rhythm test',
      'flicker detection test',
      'pulse detection test',
      'visual temporal perception',
      'critical flicker frequency test',
      'temporal visual acuity',
      'visual rhythm drill',
      'visual anomaly detection',
      'temporal processing test',
      'visual flicker test',
    ],
    locales: {
      ja: {
        term: '視覚リズム テスト',
        anchor: '視覚リズムテスト・時間弁別トレーニング',
        also: ['視覚時間知覚', 'フリッカーテスト', '時間分解能 検査', '位相差 検出', '周期知覚 訓練'],
      },
      ko: {
        term: '시각 리듬 검사',
        anchor: '시각 리듬 검사・시간 분해능 훈련',
        also: ['시간 변별 검사', '플리커 검사', '시각 시간 지각', '주기 이상 판별', '동적 시각 타이밍'],
      },
      de: {
        term: 'visueller rhythmus test',
        anchor: 'Visueller Rhythmus Test Temporale Diskrimination',
        also: ['zeitliche diskrimination test', 'flimmerverschmelzungsfrequenz test', 'visuelle zeitwahrnehmung', 'flimmertest online'],
      },
    },
  },
  '/drills/visual/visual-recognition/visual-search': {
    term: 'visual search test',
    volume: null,
    anchor: 'Conjunctive Visual Search Test',
    also: [
      'conjunctive visual search',
      'visual search task',
      'feature search test',
      'visual scanning test',
      'target discrimination drill',
      'symbol search test',
      'visual inspection test',
      'guided visual search',
      'selective attention search',
      'visual search speed test',
    ],
    locales: {
      ja: {
        term: '視覚探索 テスト',
        anchor: '視覚探索テスト・結合特徴走査トレーニング',
        also: ['視覚探索 課題', '結合探索 テスト', '視覚的注意 訓練', '特徴統合理論 トレイスマン', 'サッケード 視覚走査'],
      },
      ko: {
        term: '시각 탐색 검사',
        anchor: '시각 탐색 검사・결합 특징 스캐닝 훈련',
        also: ['결합 탐색 과제', '시각적 주의력 검사', '특징 통합 이론', '주변시 스캐닝', '목표물 식별 훈련'],
      },
      de: {
        term: 'visuelle suche test',
        anchor: 'Visuelle Suche Test Konjunktive Merkmalsintegration',
        also: ['konjunktive suche test', 'visuelle aufmerksamkeit test', 'merkmalsintegration theorie', 'visuelles scanning training'],
      },
    },
  },

  // ---------------- VISUAL TRACKING ----------------
  '/drills/visual-tracking/constant-slow-pursuit': {
    term: 'smooth pursuit eye exercise',
    anchor: 'Smooth Pursuit Eye Exercise',
    also: ['constant slow pursuit', 'slow tracking drill', 'eye tracking training', 'gaze stability practice'],
    locales: {
      ja: {
        term: '追従眼球運動 トレーニング',
        anchor: '追従眼球運動トレーニング・低速視覚追従テスト',
        also: ['追従性眼球運動', '眼球運動 トレーニング', 'アイトラッキング 練習', '動体視力 トレーニング', '滑動性追従運動'],
      },
      ko: {
        term: '안구 운동 훈련',
        anchor: '안구 운동 훈련・저속 시각 추적 트레이닝',
        also: ['눈 운동 훈련', '시각 추적 훈련', '에임 트래킹 연습', '스무스 퍼슈트', '동체시력 운동'],
      },
      de: {
        term: 'Augenfolgebewegung Training',
        anchor: 'Augenfolgebewegung Training Visuelle Blickstabilisation',
        also: ['augenfolgebewegungen uebungen', 'blickstabilisation uebungen', 'augentraining online', 'visuelles tracking training'],
      },
    },
  },
  '/drills/visual-tracking/directional-chaos-pursuit': {
    term: 'erratic motion eye drill',
    anchor: 'Erratic Motion Eye Drill',
    also: ['directional chaos pursuit', 'chaotic tracking practice', 'unpredictable target tracking', 'eye tracking training'],
    locales: {
      ja: {
        term: '不規則 追従性眼球運動',
        anchor: '不規則方向追従トレーニング・カオス動体視力テスト',
        also: ['カオス眼球運動', 'サッケードリカバリー', '突発的視覚追従', 'アイトラッキング 反射', '動体視力 不規則'],
      },
      ko: {
        term: '불규칙 안구 추적 훈련',
        anchor: '불규칙 안구 추적 훈련・카오스 방향 전환 테스트',
        also: ['불규칙 안구운동', '사케드 회복 훈련', '반응형 시각 추적', '에임 트래킹 불규칙', '동체시력 민첩성'],
      },
      de: {
        term: 'chaotische augenfolgebewegungen',
        anchor: 'Chaotische Augenfolgebewegung Unvorhersehbare Zielverfolgung',
        also: ['unvorhersehbares tracking training', 'sakkadische rückholbewegung', 'reaktives blickfolge training', 'augentraining erratisch'],
      },
    },
  },
  '/drills/visual-tracking/dynamic-evasion-pursuit': {
    term: 'reactive eye tracking drill',
    anchor: 'Reactive Eye Tracking Drill',
    also: ['dynamic evasion pursuit', 'evasive target pursuit', 'reaction tracking exercise', 'visual tracking games online'],
    locales: {
      ja: {
        term: '回避 追従 トレーニング',
        anchor: '標的回避追従トレーニング・動体視力リアクティブエイムテスト',
        also: ['動体視力 回避運動', 'リアクティブ エイム トレーニング', 'ストレイフ 追従 エイム', '急旋回 視線再捕捉', 'サッケード反射 トレーニング'],
      },
      ko: {
        term: '회피 표적 추적 훈련',
        anchor: '회피 표적 추적 훈련・동체시력 리액티브 에임 테스트',
        also: ['동적 회피 시선 추적', '에임 트래킹 반응속도', '반응형 안구 운동 훈련', '스트레이프 추적 에임', '급선회 타깃 추적'],
      },
      de: {
        term: 'reaktives tracking training',
        anchor: 'Reaktives Tracking Training Dynamische Ausweichziel-Verfolgung',
        also: ['ausweichende zielverfolgung', 'dynamische blickverfolgung', 'sakkadische neuzentrierung', 'strafe tracking uebungen'],
      },
    },
  },
  '/drills/visual-tracking/ghosting-suppress-pursuit': {
    term: 'eye fixation stability training',
    anchor: 'Eye Fixation Stability Training',
    also: ['ghosting suppress pursuit', 'ghosting suppression drill', 'gaze steadiness exercise', 'visual fixation practice'],
    locales: {
      ja: {
        term: '残像 抑制 トレーニング',
        anchor: '残像抑制固視トレーニング・動体視力視線安定性テスト',
        also: ['動体視力 残像', '固視微動 トレーニング', '視線固視 安定性', 'アイトラッキング 残像抑制', 'モーションスミア 抑制'],
      },
      ko: {
        term: '잔상 억제 시선 고정 훈련',
        anchor: '잔상 억제 시선 고정 훈련・동체시력 고정 안정성 테스트',
        also: ['안구 고정 안정성 검사', '동체시력 잔상 제거', '모션 블러 시각 훈련', '시선 고정력 테스트', '미세사케드 고정 훈련'],
      },
      de: {
        term: 'fixationsstabilitaet sehtraining',
        anchor: 'Fixationsstabilität Sehtraining Bewegungsunschärfe Unterdrückung',
        also: ['bewegungsunschaerfe unterdrueckung', 'blickstabilisation training', 'foveale fixierung uebungen', 'visuelle nachbilder reduzieren'],
      },
    },
  },
  '/drills/visual-tracking/infinity-pursuit': {
    term: 'figure-8 eye tracking exercise',
    anchor: 'Figure-8 Eye Tracking Exercise',
    also: ['infinity pursuit', 'infinity loop tracking', 'lazy eight eye drill', 'smooth pursuit training'],
    locales: {
      ja: {
        term: '8の字 眼球運動',
        anchor: '8の字眼球運動トレーニング・インフィニティ視覚追従テスト',
        also: ['8の字 目の体操', '両眼協調性 トレーニング', '正中線交差 視覚トレーニング', 'ビジョントレーニング 8の字', '眼筋トレーニング 追従'],
      },
      ko: {
        term: '8자 안구 운동',
        anchor: '8자 안구 운동 훈련・인피니티 시각 추적 테스트',
        also: ['8자 눈 운동', '양안 협응 운동', '정중선 교차 안구 훈련', '비전트레이닝 8자 운동', '원활추종 8자 검사'],
      },
      de: {
        term: 'liegende acht augentraining',
        anchor: 'Liegende Acht Augentraining Achter-Schleifen-Blickübung',
        also: ['achter schleife augenuebung', 'binokulare koordination training', 'mittellinienkreuzung blickuebung', 'augentraining liegende 8'],
      },
    },
  },
  '/drills/visual-tracking/momentum-teleport-pursuit': {
    term: 'anticipatory eye tracking drill',
    anchor: 'Anticipatory Eye Tracking Drill',
    also: ['momentum teleport pursuit', 'target reacquisition practice', 'momentum prediction drill', 'saccade recovery training'],
    locales: {
      ja: {
        term: 'テレポート エイム 練習',
        anchor: 'テレポート追従エイムトレーニング・サッケード再捕捉テスト',
        also: ['サッケード 再捕捉 トレーニング', '瞬間移動 視覚追従', '動体視力 視線跳躍 訓練', 'ターゲット再捕捉 練習', '慣性追従 動体視力'],
      },
      ko: {
        term: '순간이동 에임 연습',
        anchor: '순간이동 에임 연습・타겟 재포착 안구 추적 테스트',
        also: ['타겟 재포착 훈련', '사케드 도약 추적', '관성 예측 에임 트레이닝', '동체시력 도약 안구운동', '위치 이동 타깃 추적'],
      },
      de: {
        term: 'sprungziel tracking training',
        anchor: 'Sprungziel Tracking Training Sakkadische Reakquisition',
        also: ['sakkadische reakquisition', 'ziel neuzentrierung sehtraining', 'antizipatives tracking training', 'schnelle blickspruenge uebung'],
      },
    },
  },
  '/drills/visual-tracking/peripheral-ping-pursuit': {
    term: 'peripheral vision training',
    anchor: 'Peripheral Vision Training Drill',
    also: ['peripheral ping pursuit', 'peripheral awareness exercise', 'wide field vision drill', 'peripheral vision test'],
    locales: {
      ja: {
        term: '周辺視野 トレーニング',
        anchor: '周辺視野ピン追従トレーニング・中心視周辺視統合テスト',
        also: ['周辺視野 拡大', '中心視 周辺視 同時', '視野拡大 トレーニング', '動体視力 周辺視野 テスト', '視覚的注意 分配'],
      },
      ko: {
        term: '주변시 훈련',
        anchor: '주변시 핑 추적 훈련・중심시 주변시 통합 테스트',
        also: ['주변시야 운동', '중심시 주변시 동시 훈련', '시야각 넓히기', '분할 주의력 훈련', '동체시력 주변시 테스트'],
      },
      de: {
        term: 'peripheres sehen trainieren',
        anchor: 'Peripheres Sehen Training Peripherer Ping Blickfeld',
        also: ['peripheres blickfeld uebungen', 'gesichtsfeld erweiterung training', 'zentrales und peripheres sehen', 'tunnelblick abbauen training'],
      },
    },
  },
  '/drills/visual-tracking/predictive-pursuit': {
    term: 'predictive eye tracking drill',
    anchor: 'Predictive Eye Tracking Drill',
    also: ['predictive pursuit', 'predictive smooth pursuit', 'occlusion prediction training', 'trajectory anticipation drill', 'eye tracking accuracy'],
  },
  '/drills/visual-tracking/sine-wave-pursuit': {
    term: 'smooth pursuit eye training',
    anchor: 'Sine Wave Pursuit Training',
    also: ['sine wave pursuit', 'sine wave pursuit training', 'wave tracking exercise', 'oscillating target drill', 'eye tracking training'],
  },
  '/drills/visual-tracking/spatial-shift-pursuit': {
    term: 'adaptive eye tracking drill',
    anchor: 'Adaptive Eye Tracking Drill',
    also: ['spatial shift pursuit', 'adaptive eye tracking', 'spatial shift exercise', 'context switching tracking', 'visual adaptation drill'],
  },
  '/drills/visual-tracking/split-screen-tracking': {
    term: 'divided attention eye test',
    anchor: 'Divided Attention Eye Test',
    also: ['split-screen tracking', 'divided attention tracking', 'dual target tracking drill', 'split screen tracking', 'attention splitting exercise'],
  },
  '/drills/visual-tracking/staircase-step': {
    term: 'vertical eye tracking exercise',
    anchor: 'Vertical Eye Tracking Exercise',
    also: ['staircase step', 'vertical zig-zag pursuit', 'staircase step pursuit', 'vertical smooth pursuit', 'vertical zig-zag drill', 'staircase gaze training', 'y-axis eye movement'],
  },
  '/drills/visual-tracking/strobe-prediction-pursuit': {
    term: 'strobe vision training',
    anchor: 'Strobe Vision Training Drill',
    also: ['strobe prediction pursuit', 'stroboscopic training drill', 'strobe eye tracking', 'occluded target tracking', 'intermittent vision practice', 'strobe prediction exercise', 'stroboscopic eye training'],
  },
  '/drills/visual-tracking/triangular-pursuit': {
    term: 'eye tracking accuracy drill',
    anchor: 'Eye Tracking Accuracy Drill',
    also: ['triangular pursuit', 'triangular tracking drill', 'angular pursuit training', 'triangular vector pursuit', 'geometric smooth pursuit', 'triangular path tracking', 'gaze precision exercise'],
  },
  '/drills/visual-tracking/zig-zag-path-pursuit': {
    term: 'eye tracking coordination drill',
    anchor: 'Eye Tracking Coordination Drill',
    also: ['zig-zag path pursuit', 'zig-zag pursuit', 'zigzag pursuit drill', 'zig-zag path tracking', 'saccadic direction drill', 'angular tracking practice', 'acute corner tracking drill'],
  },
};

export function getDrillSeo(href, locale) {
  const entry = DRILL_SEO[href];
  if (!entry) return null;
  if (locale && entry.locales?.[locale]) {
    const loc = entry.locales[locale];
    return {
      term: loc.term || entry.term,
      anchor: loc.anchor || entry.anchor,
      also: loc.also || entry.also,
    };
  }
  return entry;
}
