// lib/drillSEOConfig.js
// SEO configuration for all drills - optimized for Google search ranking
// Names use high-volume search keywords for ranking

export const DRILL_SEO_CONFIG = {
  // ============ FPS DRILLS ============
  'flick-shot-training': {
    name: 'Flick Shot Training - Aim Trainer for Valorant CS2',
    title: 'Flick Shot Trainer - Free Aim Training for FPS Gamers | SkillDrills',
    description: 'Free flick shot trainer to improve your aim in FPS games like Valorant, CS2, and Overwatch. Practice flicks with speed and precision scoring. No download required.',
    keywords: ['flick shot trainer', 'aim trainer', 'fps aim practice', 'valorant aim trainer', 'cs2 aim practice', 'mouse accuracy', 'flick aim drill'],
    drillName: 'Flick Shot Trainer - Valorant & CS2 Aim',
  },
  'target-acquisition': {
    name: 'Target Acquisition Trainer - FPS Reaction Speed',
    title: 'Target Acquisition Trainer - Improve FPS Reaction Speed | SkillDrills',
    description: 'Free target acquisition trainer to improve your reaction speed and first-shot accuracy for FPS gaming. Practice acquiring and hitting targets under time pressure.',
    keywords: ['target acquisition', 'fps target practice', 'reaction speed trainer', 'first shot accuracy', 'aim drill fps'],
    drillName: 'Target Acquisition - FPS Reaction Trainer',
  },
  'strafe-tracking': {
    name: 'Strafe Tracking - Aim Trainer for Valorant CS2 Apex',
    title: 'Strafe Tracking Trainer - Smooth Aim Practice | SkillDrills',
    description: 'Free strafe tracking trainer for FPS gamers. Practice smooth mouse tracking against strafing targets. Perfect for Valorant, CS2, Apex Legends aim training.',
    keywords: ['strafe tracking', 'aim tracking trainer', 'smooth aim practice', 'valorant tracking', 'cs2 tracking drill', 'mouse control'],
    drillName: 'Strafe Tracking - Smooth Aim Trainer',
  },
  'vertical-air-track': {
    name: 'Vertical Aim Trainer - FPS Air Track Practice',
    title: 'Vertical Aim Trainer - Free FPS Aim Drill | SkillDrills',
    description: 'Free vertical aim trainer to improve your up-down tracking for FPS games. Essential for Apex Legends, Fortnite, and other vertical-combat games.',
    keywords: ['vertical aim trainer', 'air track trainer', 'fps vertical aim', 'apex legends aim', 'fortnite aim practice'],
    drillName: 'Vertical Aim Trainer - Air Track',
  },
  'angle-hold-trainer': {
    name: 'Angle Hold Trainer - Pre-Aim Crosshair Placement',
    title: 'Angle Hold Trainer - Pre-Aim Practice for FPS | SkillDrills',
    description: 'Free angle hold trainer for FPS games. Practice holding angles and snapping to targets. Improve your crosshair placement for Valorant and CS2.',
    keywords: ['angle hold trainer', 'crosshair placement', 'pre-aim practice', 'valorant crosshair', 'cs2 angle holding'],
    drillName: 'Angle Hold - Crosshair Placement Trainer',
  },
  'recoil-control': {
    name: 'Recoil Control Trainer - Spray Pattern Practice',
    title: 'Recoil Control Trainer - Spray Pattern Practice | SkillDrills',
    description: 'Free recoil control trainer to master spray patterns and weapon recoil in FPS games. Practice pulling down for perfect spray control.',
    keywords: ['recoil control', 'spray pattern trainer', 'recoil practice', 'fps weapon control', 'valorant spray', 'cs2 recoil'],
    drillName: 'Recoil Control - Spray Pattern Trainer',
  },
  'evasive-slide-track': {
    name: 'Evasive Target Tracking - Advanced FPS Aim',
    title: 'Evasive Target Tracking - Advanced FPS Aim | SkillDrills',
    description: 'Free evasive target tracking trainer. Practice tracking unpredictable moving targets for advanced FPS aim training.',
    keywords: ['evasive target tracking', 'advanced aim trainer', 'unpredictable tracking', 'fps aim drill', 'competitive aim practice'],
    drillName: 'Evasive Tracking - Advanced FPS Aim',
  },
  '180-degree-awareness': {
    name: 'Situational Awareness Trainer - 180 Flick Shot',
    title: 'Situational Awareness Trainer - FPS Game Sense | SkillDrills',
    description: 'Free situational awareness trainer for FPS gamers. Practice 180-degree flick shots and peripheral target acquisition.',
    keywords: ['situational awareness', '180 flick trainer', 'fps game sense', 'peripheral vision training', 'valorant awareness'],
    drillName: '180 Situational Awareness - FPS Game Sense',
  },
  'target-prioritization': {
    name: 'Target Prioritization - FPS Decision Making',
    title: 'Target Prioritization Trainer - FPS Decision Making | SkillDrills',
    description: 'Free target prioritization trainer. Practice selecting the most threatening target in multi-target scenarios.',
    keywords: ['target prioritization', 'fps decision making', 'multi-target trainer', 'threat assessment', 'competitive fps training'],
    drillName: 'Target Prioritization - FPS Decision Trainer',
  },
  'target-switching-swarm': {
    name: 'Target Switching - Multi-Target Aim Trainer',
    title: 'Target Switching Trainer - Swarm Aim Practice | SkillDrills',
    description: 'Free target switching swarm trainer. Practice rapidly switching between multiple targets under pressure.',
    keywords: ['target switching', 'swarm trainer', 'multi-target aim', 'rapid target acquisition', 'fps tracking drill'],
    drillName: 'Target Switching - Multi-Target Trainer',
  },
  'pro-smooth-pursuit': {
    name: 'Smooth Pursuit - Professional Aim Tracking',
    title: 'Smooth Pursuit Trainer - Professional Aim Training | SkillDrills',
    description: 'Free smooth pursuit trainer for professional FPS aim training. Practice perfectly smooth mouse tracking against moving targets.',
    keywords: ['smooth pursuit', 'professional aim trainer', 'tracking practice', 'mouse smoothness', 'precision aim'],
    drillName: 'Pro Smooth Pursuit - Professional Tracking',
  },
  'high-speed-kinetic-trainer': {
    name: 'Kinetic Aim Trainer - High Speed FPS Drills',
    title: 'Kinetic Aim Trainer - High Speed FPS Drills | SkillDrills',
    description: 'Free high speed kinetic aim trainer. Practice fast-paced target acquisition and tracking at high velocities.',
    keywords: ['kinetic trainer', 'high speed aim', 'fast target acquisition', 'reaction speed trainer', 'fps muscle memory'],
    drillName: 'Kinetic Speed Trainer - Fast FPS Aim',
  },
  'instant-response': {
    name: 'Instant Response - Reflex Training for FPS',
    title: 'Instant Response Trainer - Reflex Training for FPS | SkillDrills',
    description: 'Free instant response trainer for FPS gamers. Practice lightning-fast reactions to unexpected targets.',
    keywords: ['instant response trainer', 'reflex aim', 'reaction time fps', 'quick aim trainer', 'fps reflex drill'],
    drillName: 'Instant Response - FPS Reflex Trainer',
  },
  'pro-tracking': {
    name: 'Pro Aim Tracking - Professional FPS Training',
    title: 'Pro Aim Tracking Trainer - Professional FPS Training | SkillDrills',
    description: 'Free professional aim tracking trainer. Practice smooth, consistent crosshair tracking against complex movement patterns.',
    keywords: ['pro tracking', 'professional aim trainer', 'tracking accuracy', 'smooth crosshair', 'fps training pro'],
    drillName: 'Pro Aim Tracker - Professional FPS Training',
  },

  // ============ COGNITIVE DRILLS ============
  'divided-attention': {
    name: 'Divided Attention - Dual Task Brain Training',
    title: 'Divided Attention Drill - Dual Task Brain Training | SkillDrills',
    description: 'Free divided attention drill for cognitive dual task training. Click moving targets while monitoring a number stream. Improve multitasking, cognitive flexibility, and processing speed.',
    keywords: ['divided attention drill', 'dual task training', 'multitasking brain training', 'cognitive drill free', 'attention training', 'brain training game', 'focus exercise'],
    drillName: 'Divided Attention - Dual Task Brain Trainer',
  },
  'selective-attention': {
    name: 'Selective Attention - Focus Training Drill',
    title: 'Selective Attention Drill - Focus Training | SkillDrills',
    description: 'Free selective attention drill to improve your ability to focus on relevant information while ignoring distractions.',
    keywords: ['selective attention', 'focus training', 'distraction resistance', 'concentration drill', 'cognitive training'],
    drillName: 'Selective Attention - Focus Training',
  },
  'sustained-attention': {
    name: 'Sustained Attention - Focus Endurance Training',
    title: 'Sustained Attention Drill - Endurance Focus Training | SkillDrills',
    description: 'Free sustained attention drill for building long-duration focus endurance. Train your brain to maintain concentration.',
    keywords: ['sustained attention', 'focus endurance', 'concentration training', 'attention span', 'long focus drill'],
    drillName: 'Sustained Attention - Focus Endurance',
  },
  'concentration-grid': {
    name: 'Concentration Grid - Focus and Speed Practice',
    title: 'Concentration Grid - Focus and Processing Speed | SkillDrills',
    description: 'Free concentration grid drill to improve focus and processing speed. Find numbers in sequence under time pressure.',
    keywords: ['concentration grid', 'focus grid', 'number search', 'processing speed', 'mental agility', 'brain training game'],
    drillName: 'Concentration Grid - Focus Speed Drill',
  },
  'distraction-fighter': {
    name: 'Distraction Fighter - Mental Resilience Training',
    title: 'Distraction Fighter - Resilience Training | SkillDrills',
    description: 'Free distraction fighter drill to build mental resilience against interruptions. Practice maintaining focus despite active distractions.',
    keywords: ['distraction fighter', 'mental resilience', 'focus training', 'interruption resistance', 'deep work training'],
    drillName: 'Distraction Fighter - Resilience Training',
  },
  'focus-timer': {
    name: 'Focus Timer - Pomodoro Concentration Tool',
    title: 'Focus Timer - Pomodoro Style Concentration | SkillDrills',
    description: 'Free focus timer for structured concentration sessions. Train your ability to maintain deep focus with timed intervals.',
    keywords: ['focus timer', 'pomodoro timer', 'concentration timer', 'deep work timer', 'productivity tool'],
    drillName: 'Focus Timer - Pomodoro Concentrator',
  },
  'logic-puzzles': {
    name: 'Logic Puzzles - Free Brain Training Games',
    title: 'Logic Puzzles - Free Brain Training Games | SkillDrills',
    description: 'Free logic puzzles to train your problem-solving and deductive reasoning skills.',
    keywords: ['logic puzzles', 'brain training', 'reasoning puzzles', 'deductive reasoning', 'problem solving game'],
    drillName: 'Logic Puzzles - Brain Training Games',
  },
  'quick-math': {
    name: 'Quick Math - Mental Arithmetic Speed Test',
    title: 'Quick Math - Mental Arithmetic Speed Test | SkillDrills',
    description: 'Free quick math drill to improve mental arithmetic speed. Solve math problems under time pressure.',
    keywords: ['quick math', 'mental arithmetic', 'math speed test', 'brain math', 'calculation practice'],
    drillName: 'Quick Math - Mental Speed Test',
  },
  'reaction-time': {
    name: 'Reaction Time Test - Visual Response Speed',
    title: 'Reaction Time Test - Visual Response Trainer | SkillDrills',
    description: 'Free reaction time test to measure and improve your visual response speed.',
    keywords: ['reaction time test', 'reaction speed', 'visual reaction', 'reflex test', 'response time'],
    drillName: 'Reaction Time - Visual Response Test',
  },
  'symbol-matching': {
    name: 'Symbol Matching - Cognitive Processing Speed',
    title: 'Symbol Matching - Cognitive Processing Speed | SkillDrills',
    description: 'Free symbol matching drill to improve cognitive processing speed and visual recognition.',
    keywords: ['symbol matching', 'cognitive speed', 'pattern matching', 'visual recognition', 'processing speed'],
    drillName: 'Symbol Matching - Processing Speed Drill',
  },

  // ============ MEMORY DRILLS ============
  'card-matching': {
    name: 'Memory Card Matching Game - Brain Training',
    title: 'Memory Card Matching Game - Free Brain Training | SkillDrills',
    description: 'Free memory card matching game to improve visual memory and recall speed.',
    keywords: ['card matching game', 'memory game', 'visual memory', 'matching pairs', 'brain training game'],
    drillName: 'Memory Card Matching - Visual Recall Game',
  },
  'memory-sequence': {
    name: 'Memory Sequence - Simon Says Brain Game',
    title: 'Memory Sequence Game - Improve Short Term Memory | SkillDrills',
    description: 'Free memory sequence game inspired by Simon Says. Remember and repeat increasingly long sequences.',
    keywords: ['memory sequence', 'simon says game', 'short term memory', 'working memory training', 'sequence recall'],
    drillName: 'Memory Sequence - Simon Says Brain Game',
  },
  'digit-span': {
    name: 'Digit Span Test - Working Memory Assessment',
    title: 'Digit Span Test - Working Memory Assessment | SkillDrills',
    description: 'Free digit span test to assess and train your working memory capacity.',
    keywords: ['digit span test', 'working memory test', 'digit recall', 'memory assessment', 'brain training'],
    drillName: 'Digit Span - Working Memory Test',
  },
  'n-back': {
    name: 'Dual N-Back - Working Memory Training Game',
    title: 'Dual N-Back Game - Working Memory Training | SkillDrills',
    description: 'Free dual n-back game for working memory training. The most scientifically supported brain training exercise.',
    keywords: ['dual n back', 'n back game', 'working memory training', 'brain training', 'fluid intelligence'],
    drillName: 'Dual N-Back - Working Memory Trainer',
  },
  'number-recall': {
    name: 'Number Recall Test - Numerical Memory Drill',
    title: 'Number Recall Test - Numerical Memory | SkillDrills',
    description: 'Free number recall drill to improve your numerical memory.',
    keywords: ['number recall', 'numerical memory', 'digit memory', 'number sequence', 'memory training'],
    drillName: 'Number Recall - Memory Challenge',
  },
  'word-recall': {
    name: 'Word Recall Test - Verbal Memory Training',
    title: 'Word Recall Test - Verbal Memory Training | SkillDrills',
    description: 'Free word recall drill to improve verbal memory.',
    keywords: ['word recall', 'verbal memory', 'memory test', 'word list memory', 'language memory'],
    drillName: 'Word Recall - Verbal Memory Test',
  },
  'color-sequence': {
    name: 'Color Sequence Memory Game - Visual Recall',
    title: 'Color Sequence Memory Game - Visual Recall | SkillDrills',
    description: 'Free color sequence memory game to train visual short-term memory.',
    keywords: ['color sequence', 'visual memory game', 'color recall', 'sequence memory', 'brain game'],
    drillName: 'Color Sequence - Visual Memory Game',
  },

  // ============ ACADEMIC DRILLS ============
  'typing-test': {
    name: 'Free Typing Speed Test - Check Your WPM',
    title: 'Free Typing Speed Test - Check Your WPM | SkillDrills',
    description: 'Free typing speed test to check your words per minute (WPM) and accuracy. Practice with quotes across multiple levels.',
    keywords: ['typing speed test', 'free typing test', 'wpm test', 'typing practice', 'keyboard speed'],
    drillName: 'Typing Speed Test - Free WPM Checker',
  },
  'code-typing': {
    name: 'Code Typing Practice - Programmer WPM Test',
    title: 'Code Typing Practice - Programmer Typing Test | SkillDrills',
    description: 'Free code typing practice for programmers. Type real code snippets across multiple programming languages.',
    keywords: ['code typing', 'programmer typing test', 'coding speed', 'developer typing', 'typing practice code'],
    drillName: 'Code Typing - Developer Speed Test',
  },
  'mental-math': {
    name: 'Mental Math Practice - Quick Calculation',
    title: 'Mental Math Practice - Quick Calculation Training | SkillDrills',
    description: 'Free mental math practice to improve your quick calculation skills. Perfect for SAT, GRE, and exam preparation.',
    keywords: ['mental math', 'quick calculation', 'arithmetic practice', 'brain math', 'math speed test', 'exam preparation'],
    drillName: 'Mental Math - Quick Calculation Trainer',
  },
  'arithmetic-race': {
    name: 'Arithmetic Race - Speed Math Challenge',
    title: 'Arithmetic Race - Speed Math Challenge | SkillDrills',
    description: 'Free arithmetic race drill to improve speed math skills under time pressure.',
    keywords: ['arithmetic race', 'speed math', 'math challenge', 'mental calculation', 'math practice'],
    drillName: 'Arithmetic Race - Speed Math',
  },
  'reading-comprehension': {
    name: 'Reading Comprehension Practice - Free Test',
    title: 'Reading Comprehension Practice - Free Test | SkillDrills',
    description: 'Free reading comprehension practice to improve understanding and retention.',
    keywords: ['reading comprehension', 'reading practice', 'comprehension test', 'reading skills', 'study skills'],
    drillName: 'Reading Comprehension - Free Practice',
  },
  'inference-drill': {
    name: 'Inference Practice - Critical Reasoning Drill',
    title: 'Inference Practice - Critical Reasoning Drill | SkillDrills',
    description: 'Free inference drill to improve critical reasoning and deductive thinking skills.',
    keywords: ['inference drill', 'critical reasoning', 'deductive thinking', 'logic practice', 'reasoning skills'],
    drillName: 'Inference Drill - Critical Reasoning',
  },
  'speed-reader': {
    name: 'Speed Reading Practice - Free Online Test',
    title: 'Speed Reading Practice - Free Online Test | SkillDrills',
    description: 'Free speed reading practice to improve reading speed and comprehension.',
    keywords: ['speed reading', 'reading speed test', 'speed reader', 'reading practice', 'fast reading'],
    drillName: 'Speed Reading - Free Online Practice',
  },
  'multiplication-tables': {
    name: 'Multiplication Tables - Math Practice Game',
    title: 'Multiplication Tables Practice - Math Game | SkillDrills',
    description: 'Free multiplication tables practice to master times tables quickly.',
    keywords: ['multiplication tables', 'times tables', 'math practice', 'multiplication game', 'learn times tables'],
    drillName: 'Multiplication Tables - Times Table Mastery',
  },

  // ============ VISUAL DRILLS ============
  'light-reaction': {
    name: 'Reaction Time Test - Visual Response Trainer',
    title: 'Reaction Time Test - Visual Response Trainer | SkillDrills',
    description: 'Free reaction time test to measure and improve your visual response speed.',
    keywords: ['reaction time test', 'reaction speed', 'visual reaction', 'reflex test', 'response time'],
    drillName: 'Reaction Time - Visual Response Test',
  },
  'go/no-go': {
    name: 'Go No-Go Test - Inhibitory Control Training',
    title: 'Go No-Go Test - Inhibitory Control Training | SkillDrills',
    description: 'Free go no-go test to improve inhibitory control and response inhibition.',
    keywords: ['go no go test', 'inhibitory control', 'response inhibition', 'executive function', 'cognitive control'],
    drillName: 'Go No-Go - Response Control Test',
  },
  'peripheral-flash': {
    name: 'Peripheral Vision Test - Awareness Training',
    title: 'Peripheral Vision Test - Awareness Training | SkillDrills',
    description: 'Free peripheral vision test and training drill. Detect and respond to stimuli in your peripheral field.',
    keywords: ['peripheral vision test', 'situational awareness', 'peripheral training', 'vision drill', 'reaction training'],
    drillName: 'Peripheral Vision - Field Awareness Test',
  },
  'wide-field': {
    name: 'Wide Field Vision - Peripheral Awareness',
    title: 'Wide Field Vision - Peripheral Awareness | SkillDrills',
    description: 'Free wide field vision training to expand your peripheral awareness.',
    keywords: ['wide field vision', 'peripheral awareness', 'field of view training', 'vision drill', 'situational awareness'],
    drillName: 'Wide Field - Peripheral Vision Drill',
  },
  'moving-target': {
    name: 'Moving Target Trainer - Kinetic Intercept',
    title: 'Moving Target Trainer - Kinetic Intercept | SkillDrills',
    description: 'Free moving target trainer to practice intercepting moving objects.',
    keywords: ['moving target', 'kinetic intercept', 'timing practice', 'prediction training', 'hand eye coordination'],
    drillName: 'Moving Target - Kinetic Interceptor',
  },
  'multiple-targets': {
    name: 'Multiple Target Tracking - Visual Processing',
    title: 'Multiple Target Tracking - Visual Processing | SkillDrills',
    description: 'Free multiple target tracking drill to improve visual attention and processing.',
    keywords: ['multiple target tracking', 'visual attention', 'multi-object tracking', 'peripheral vision', 'cognitive training'],
    drillName: 'Multiple Target - Visual Tracking Drill',
  },
  'pursuit-tracker': {
    name: 'Pursuit Tracker - Smooth Eye Movement',
    title: 'Pursuit Tracker - Smooth Eye Movement | SkillDrills',
    description: 'Free pursuit tracker drill to improve smooth visual pursuit and tracking.',
    keywords: ['pursuit tracker', 'smooth pursuit', 'eye tracking', 'visual tracking', 'motion tracking'],
    drillName: 'Pursuit Tracker - Smooth Visual Tracking',
  },
  'difference-spotter': {
    name: 'Difference Spotter - Visual Comparison Test',
    title: 'Difference Spotter - Visual Comparison Test | SkillDrills',
    description: 'Free difference spotter drill to improve visual comparison and attention to detail.',
    keywords: ['difference spotter', 'spot the difference', 'visual comparison', 'attention to detail', 'visual perception'],
    drillName: 'Difference Spotter - Find the Difference',
  },
  'rapid-object-id': {
    name: 'Rapid Object ID - Visual Recognition Speed',
    title: 'Rapid Object ID - Visual Recognition Speed | SkillDrills',
    description: 'Free rapid object identification drill to improve visual recognition speed.',
    keywords: ['rapid object id', 'visual recognition', 'object identification', 'speed of processing', 'visual perception'],
    drillName: 'Rapid Object ID - Visual Speed Test',
  },
  'visual-search': {
    name: 'Visual Search Test - Scanning Speed Drill',
    title: 'Visual Search Test - Scanning Speed Drill | SkillDrills',
    description: 'Free visual search test to improve scanning speed and target detection.',
    keywords: ['visual search', 'scanning speed', 'target detection', 'visual scanning', 'search test'],
    drillName: 'Visual Search - Scanning Speed Test',
  },
  'distance-judgment': {
    name: 'Distance Judgment - Depth Perception Test',
    title: 'Distance Judgment - Depth Perception Test | SkillDrills',
    description: 'Free distance judgment drill to improve depth perception and spatial awareness.',
    keywords: ['distance judgment', 'depth perception', 'spatial awareness', 'distance estimation', 'visual perception'],
    drillName: 'Distance Judgment - Depth Perception',
  },
  'sound-reaction': {
    name: 'Sound Reaction Test - Auditory Response',
    title: 'Sound Reaction Test - Auditory Response | SkillDrills',
    description: 'Free sound reaction test to measure and improve auditory response speed.',
    keywords: ['sound reaction', 'auditory response', 'reaction time', 'sound reflex', 'hearing test'],
    drillName: 'Sound Reaction - Auditory Speed Test',
  },

  // ============ MOTOR DRILLS ============
  'aim-trainer': {
    name: 'Mouse Aim Trainer - Click Accuracy Practice',
    title: 'Mouse Aim Trainer - Click Accuracy Practice | SkillDrills',
    description: 'Free mouse aim trainer to improve click accuracy and precision.',
    keywords: ['mouse aim trainer', 'click accuracy', 'precision clicking', 'mouse control', 'aim practice'],
    drillName: 'Mouse Aim Trainer - Click Accuracy',
  },
  'click-accuracy': {
    name: 'Click Accuracy Test - Precision Mouse Control',
    title: 'Click Accuracy Test - Fine Motor Control | SkillDrills',
    description: 'Free click accuracy test to measure and improve fine motor control.',
    keywords: ['click accuracy', 'fine motor control', 'precision test', 'mouse accuracy', 'target clicking'],
    drillName: 'Click Accuracy - Precision Test',
  },
  'drag-and-drop': {
    name: 'Drag and Drop - Motor Coordination Test',
    title: 'Drag and Drop - Motor Coordination Test | SkillDrills',
    description: 'Free drag and drop trainer to improve hand-eye coordination and fine motor control.',
    keywords: ['drag and drop', 'motor coordination', 'hand eye coordination', 'fine motor skills', 'mouse control'],
    drillName: 'Drag and Drop - Motor Coordination',
  },
  'finger-sequencing': {
    name: 'Finger Sequencing - Motor Speed Test',
    title: 'Finger Sequencing - Motor Speed Test | SkillDrills',
    description: 'Free finger sequencing drill to improve finger dexterity and motor speed.',
    keywords: ['finger sequencing', 'finger dexterity', 'motor speed', 'typing dexterity', 'finger coordination'],
    drillName: 'Finger Sequencing - Dexterity Test',
  },
  'gesture-speed': {
    name: 'Gesture Speed - Movement Reaction Test',
    title: 'Gesture Speed - Movement Reaction Test | SkillDrills',
    description: 'Free gesture speed drill to improve movement reaction time.',
    keywords: ['gesture speed', 'movement reaction', 'motor response', 'reaction time', 'hand speed'],
    drillName: 'Gesture Speed - Movement Test',
  },
  'rapid-tapping': {
    name: 'Rapid Tapping - Finger Speed Test',
    title: 'Rapid Tapping - Finger Speed Test | SkillDrills',
    description: 'Free rapid tapping drill to measure and improve finger tapping speed.',
    keywords: ['rapid tapping', 'finger speed test', 'tapping speed', 'finger dexterity', 'motor speed'],
    drillName: 'Rapid Tapping - Finger Speed Test',
  },
  'synchronization': {
    name: 'Synchronization - Timing Accuracy Test',
    title: 'Synchronization - Timing Accuracy Test | SkillDrills',
    description: 'Free synchronization drill to improve timing accuracy and rhythm.',
    keywords: ['synchronization', 'timing accuracy', 'rhythm test', 'motor timing', 'coordination drill'],
    drillName: 'Synchronization - Timing Test',
  },
  'stopwatch-click': {
    name: 'Stopwatch Click - Time Estimation Test',
    title: 'Stopwatch Click - Time Estimation Test | SkillDrills',
    description: 'Free stopwatch click drill to improve time estimation accuracy.',
    keywords: ['stopwatch click', 'time estimation', 'timing accuracy', 'reaction time', 'motor timing'],
    drillName: 'Stopwatch Click - Time Test',
  },
  'rhythm-tap': {
    name: 'Rhythm Tap - Beat Synchronization Test',
    title: 'Rhythm Tap - Beat Synchronization Test | SkillDrills',
    description: 'Free rhythm tap drill to improve beat synchronization and motor timing.',
    keywords: ['rhythm tap', 'beat synchronization', 'rhythm test', 'motor timing', 'music rhythm'],
    drillName: 'Rhythm Tap - Beat Sync Test',
  },
  'fine-motor': {
    name: 'Fine Motor Control - Precision Task Test',
    title: 'Fine Motor Control - Precision Test | SkillDrills',
    description: 'Free fine motor control drill to improve precision and dexterity.',
    keywords: ['fine motor', 'precision control', 'dexterity test', 'motor skills', 'hand control'],
    drillName: 'Fine Motor - Precision Control',
  },
  'steady-hand': {
    name: 'Steady Hand - Tremor Control Test',
    title: 'Steady Hand - Tremor Control Test | SkillDrills',
    description: 'Free steady hand drill to improve hand stability and tremor control.',
    keywords: ['steady hand', 'tremor control', 'hand stability', 'precision test', 'motor control'],
    drillName: 'Steady Hand - Stability Test',
  },
  'tracing': {
    name: 'Tracing Test - Fine Motor Precision',
    title: 'Tracing Test - Fine Motor Precision | SkillDrills',
    description: 'Free tracing drill to improve fine motor precision and control.',
    keywords: ['tracing test', 'fine motor', 'precision tracing', 'hand control', 'motor accuracy'],
    drillName: 'Tracing - Precision Motor Test',
  },
};

/**
 * Get SEO metadata for a drill, with fallback
 */
export function getDrillSEO(drillId) {
  return DRILL_SEO_CONFIG[drillId] || {
    name: drillId.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    title: `${drillId.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())} - Free Training Drill | SkillDrills`,
    description: `Free ${drillId.replace(/-/g, ' ')} drill for training and practice. No registration required.`,
    keywords: [drillId.replace(/-/g, ' '), 'free drill', 'training', 'skill practice'],
    drillName: drillId.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
  };
}