// lib/drillSeo.js
// Per-drill search-term map. One entry per drill in lib/drillsRegistry.js.
//
// WHY THIS FILE EXISTS
// The registry's `keywords` arrays are auto-generated by splitting each drill's
// description into words, so they contain filler like "between", "while" and
// "seconds". They are fine for the on-site search index and useless as a search
// signal — and the `keywords` meta tag has been ignored by Google since 2009 and
// is treated as a spam hint by Bing, so no amount of editing it changes a ranking.
//
// The signals that do carry keyword relevance are the title, the H1, the body
// copy, and the anchor text of links pointing at the page. This file supplies
// the last of those. Until now no drill page linked to any other drill page:
// the GSC URL Inspection API showed 64 of 81 drill URLs with no referring URL
// at all, which is why they sat in "Discovered - currently not indexed".
//
// FIELDS
//   term    The primary search phrase the page is built to rank for. Taken from
//           the page's own <title>, which was keyword-researched, so this file
//           and the title do not drift apart.
//   anchor  The link text other pages use when linking here. Keyword-first and
//           unique across the whole map — two pages sharing anchor text would
//           send Google a contradictory signal about which one owns the phrase.
//   also    Secondary phrases for this drill. Used to score topical relatedness
//           when picking which drills to cross-link.
//
// Search Console query clusters this map is aligned to (180 days to 2026-08-19):
//   fps training 48 · fps practice 28 · fps trainer 16 · practice fps aim 12
//   flick trainer 19 · flick training 17 · flick aim trainer 8 · micro flick training 5
//   memory drill 19 · online memory training 14 · memory training online 11
//   drills online 42 · online drills 40
//   visual drill 4 · visual-perception drills 4 · visual tracking games online 1
//   fps warm up · fps warmup · cs2 jitter · apex legends jitter aim · gridshot 3x3 online
//   valorant aim trainer online 4 · train your brain online 4 · processing speed games online 1
//   physical drills · physical fitness drills · movement trainer · movement training game

export const DRILL_SEO = {
  // ---------------- COGNITIVE ----------------
  '/drills/cognitive/attention/concentration-stamina': {
    term: 'focus test',
    anchor: 'Focus Test',
    also: ['attention span test', 'concentration test online', 'sustained attention drill'],
  },
  '/drills/cognitive/attention/divided-attention': {
    term: 'divided attention test',
    anchor: 'Divided Attention Test',
    also: ['dual task training', 'split focus game', 'attention training online'],
  },
  '/drills/cognitive/attention/multi-tasking': {
    term: 'multitasking test',
    anchor: 'Multitasking Test',
    also: ['dual target tracking', 'brain training online', 'train your brain online'],
  },
  '/drills/cognitive/focus/concentration-grid': {
    term: 'schulte table',
    anchor: 'Schulte Table Trainer',
    also: ['concentration grid', 'number search test', 'visual search speed'],
  },
  '/drills/cognitive/focus/distraction-fighter': {
    term: 'stroop test',
    anchor: 'Stroop Test Online',
    also: ['selective attention test', 'free focus game online', 'distraction filtering drill'],
  },
  '/drills/cognitive/processing-speed/reaction-time': {
    term: 'neuro speed test',
    anchor: 'Neuro Speed & Reflex Test',
    also: ['processing speed games online', 'cognitive reaction speed', 'mental speed test'],
  },
  '/drills/cognitive/processing-speed/rsvp-reader': {
    term: 'reading speed test',
    anchor: 'Reading Speed Test',
    also: ['speed reading trainer', 'visual processing speed', 'word recognition drill'],
  },
  '/drills/cognitive/processing-speed/symbol-matching': {
    term: 'symbol digit modalities test',
    anchor: 'Symbol Digit Modalities Test',
    also: ['symbol matching test', 'digit symbol substitution', 'processing speed drill'],
  },

  // ---------------- FPS ----------------
  '/drills/fps/180-degree-awareness': {
    term: '180 aim trainer',
    anchor: '180° Snap Turn Aim Trainer',
    also: ['snap turn practice', 'fps awareness training', 'fps warm up'],
  },
  '/drills/fps/angle-hold-trainer': {
    term: 'crosshair placement trainer',
    anchor: 'Crosshair Placement Trainer',
    also: ['angle holding practice', 'pre-aim training', 'fps practice'],
  },
  '/drills/fps/anti-strafe-jitter-duel': {
    term: 'jitter aim trainer',
    anchor: 'Anti-Strafe Jitter Trainer',
    also: ['cs2 jitter', 'apex legends jitter aim', 'adad strafe practice', 'reactive tracking'],
  },
  '/drills/fps/anti-zigzag-movement-trainer': {
    term: 'anti-zigzag aim trainer',
    anchor: 'Anti-Zigzag Aim Trainer',
    also: ['evasive strafe tracking', 'slide cancel tracking', 'fps tracking practice'],
  },
  '/drills/fps/flick-shot-training': {
    term: 'flick shot trainer',
    anchor: 'Flick Shot Trainer',
    also: ['flick trainer', 'flick aim trainer', 'flick training online', 'snap aim practice', 'valorant aim trainer online'],
  },
  '/drills/fps/flow-state': {
    term: 'aim flow state trainer',
    anchor: 'Aim Flow State Trainer',
    also: ['fps focus training', 'aim endurance drill', 'fps warmup'],
  },
  '/drills/fps/instant-response': {
    term: 'fps reaction time test',
    anchor: 'FPS Reaction Time Test',
    also: ['gaming reflex test', 'click response time', 'fps reflex training'],
  },
  '/drills/fps/micro-correction-precision': {
    term: 'micro-correction aim trainer',
    anchor: 'Micro-Correction Aim Trainer',
    also: ['micro flick training', 'headshot accuracy drill', 'overflick correction'],
  },
  '/drills/fps/pro-smooth-pursuit': {
    term: 'smooth pursuit aim trainer',
    anchor: 'Smooth Pursuit Aim Trainer',
    also: ['curve tracking practice', 'fps tracking practice', 'aim tracking drill'],
  },
  '/drills/fps/recoil-control': {
    term: 'recoil control trainer',
    anchor: 'Recoil Control Trainer',
    also: ['spray pattern practice', 'recoil compensation drill', 'fps shooting practice'],
  },
  '/drills/fps/strafe-tracking': {
    term: 'strafe tracking aim trainer',
    anchor: 'Strafe Tracking Aim Trainer',
    also: ['counter-strafe reading', 'reactive tracking aim', 'fps aim training'],
  },
  '/drills/fps/target-acquisition': {
    term: 'target acquisition trainer',
    anchor: 'Target Acquisition Trainer',
    also: ['first shot accuracy', 'gridshot 3x3 online', 'fps trainer'],
  },
  '/drills/fps/target-prioritization': {
    term: 'target prioritization trainer',
    anchor: 'Target Prioritization Trainer',
    also: ['threat assessment drill', 'impulse control aim', 'fps decision training'],
  },
  '/drills/fps/target-switching-swarm': {
    term: 'target switching trainer',
    anchor: 'Target Switching Trainer',
    also: ['multi-target aim practice', 'fps training online', 'rapid target transitions'],
  },
  '/drills/fps/vertical-air-track': {
    term: 'vertical aim trainer',
    anchor: 'Vertical Aim Trainer',
    also: ['y-axis mouse control', 'aerial tracking practice', 'apex legends aim practice'],
  },

  // ---------------- MEMORY ----------------
  '/drills/memory/short-term-memory/color-sequence': {
    term: 'color memory game',
    anchor: 'Color Memory Game',
    also: ['visual memory test', 'memory drill', 'colour sequence recall'],
  },
  '/drills/memory/short-term-memory/digit-span': {
    term: 'digit span test',
    anchor: 'Digit Span Memory Test',
    also: ['number memory test', 'short term memory test', 'online memory training'],
  },
  '/drills/memory/short-term-memory/word-recall': {
    term: 'verbal memory test',
    anchor: 'Verbal Memory Test',
    also: ['word recall test', 'memory training online', 'word list recall'],
  },
  '/drills/memory/spatial-memory/grid-memorization': {
    term: 'visual memory test',
    anchor: 'Visual Memory Test',
    also: ['spatial memory test', 'visual pattern memory', 'grid recall game'],
  },
  '/drills/memory/spatial-memory/object-location': {
    term: 'object location memory test',
    anchor: 'Object Location Memory Test',
    also: ['spatial position memory', 'memory skills training', 'location recall drill'],
  },
  '/drills/memory/spatial-memory/path-tracing': {
    term: 'sequence memory game',
    anchor: 'Path Tracing Sequence Memory',
    also: ['path recall drill', 'spatial sequence memory', 'memory drill'],
  },
  '/drills/memory/working-memory/n-back': {
    term: 'n-back test',
    anchor: '3-Back Working Memory Test',
    also: ['dual n-back training', 'working memory test', 'online memory training'],
  },

  // ---------------- MOTOR ----------------
  '/drills/motor/hand-eye-coordination/aim-trainer': {
    term: 'aim trainer',
    anchor: 'Mouse Aim Trainer',
    also: ['free aim trainer', 'aim trainer online', 'mouse accuracy test', 'aim practice online'],
  },
  '/drills/motor/hand-eye-coordination/drag-and-drop': {
    term: 'drag and drop trainer',
    anchor: 'Drag & Drop Mouse Trainer',
    also: ['mouse control practice', 'cursor deceleration drill', 'movement trainer'],
  },
  '/drills/motor/hand-eye-coordination/precision-flick-shot': {
    term: 'mouse accuracy test',
    anchor: 'Mouse Accuracy Test',
    also: ['flick practice', 'bulls-eye click accuracy', 'aim flick trainer'],
  },
  '/drills/motor/movement-speed/finger-sequencing': {
    term: 'sequence aim trainer',
    anchor: 'Sequence Aim & Finger Speed Test',
    also: ['finger speed test', 'sequential target switching', 'movement training game'],
  },
  '/drills/motor/movement-speed/keyboard-recognition': {
    term: 'keyboard speed test',
    anchor: 'Keyboard Speed Test',
    also: ['keyboard reflex test', 'gaming keybind practice', 'key recognition drill'],
  },
  '/drills/motor/movement-speed/rapid-tapping': {
    term: 'cps test',
    anchor: 'CPS Test & Click Speed Test',
    also: ['click speed test', 'clicks per second test', 'cps tester'],
  },
  '/drills/motor/precision-control/steady-hand': {
    term: 'steady hand game',
    anchor: 'Steady Hand Game',
    also: ['mouse steadiness drill', 'cursor control practice', 'corridor tracing game'],
  },
  '/drills/motor/precision-control/tracing': {
    term: 'mouse tracing game',
    anchor: 'Mouse Tracing Game',
    also: ['wave tracking drill', 'smooth cursor control', 'mouse precision practice'],
  },

  // ---------------- PHYSICAL ----------------
  '/drills/physical/balance-training/stability-challenge': {
    term: 'online balance trainer',
    anchor: 'Stability & Balance Trainer',
    also: ['postural equilibrium drill', 'physical drills', 'balance training game'],
  },
  '/drills/physical/coordination/complex-pattern': {
    term: 'pattern memory game',
    anchor: 'Pattern Memory Game',
    also: ['spatial memory training', 'path redraw drill', 'visual pattern recall'],
  },
  '/drills/physical/coordination/cross-body-movement': {
    term: 'hand eye coordination game',
    anchor: 'Hand Eye Coordination Game',
    also: ['bilateral coordination drill', 'cross body movement', 'physical fitness drills'],
  },
  '/drills/physical/coordination/dynamic-grid-evasion': {
    term: 'spatial reflex trainer',
    anchor: 'Dynamic Grid Evasion Drill',
    also: ['hazard dodging game', 'rapid spatial scanning', 'reflex training online'],
  },
  '/drills/physical/fitness/agility-ladder': {
    term: 'agility ladder drills',
    anchor: 'Agility Ladder Drill',
    also: ['footwork timing drill', 'motor sequencing training', 'physical drills'],
  },
  '/drills/physical/fitness/jump-sequence': {
    term: 'reaction time training',
    anchor: 'Jump Sequence Reaction Drill',
    also: ['timing precision game', 'launch and land drill', 'reaction training online'],
  },
  '/drills/physical/fitness/speed-drill': {
    term: 'speed drill',
    anchor: 'Target Speed Drill',
    also: ['rapid tapping drill', 'target acquisition speed', 'physical fitness drills'],
  },
  '/drills/physical/reflex-training/drop-catch': {
    term: 'reflex test online',
    anchor: 'Reflex Drop Catch Test',
    also: ['ruler drop reaction test', 'catch reaction game', 'reflex test'],
  },
  '/drills/physical/reflex-training/peripheral-threat-sweeper': {
    term: 'peripheral vision test',
    anchor: 'Peripheral Vision Test',
    also: ['peripheral vision training', 'spatial awareness drill', 'radial threat scanning'],
  },
  '/drills/physical/reflex-training/quick-dodge': {
    term: 'reflex game online',
    anchor: 'Dodge Reflex Game',
    also: ['free dodge game', 'mouse dodging drill', 'reflex training game'],
  },
  '/drills/physical/reflex-training/reaction-chain': {
    term: 'impulse control reflex game',
    anchor: 'Reaction Chain Impulse Drill',
    also: ['motor inhibition training', 'precision stopping drill', 'reaction speed game'],
  },

  // ---------------- REACTION SPEED ----------------
  '/drills/reaction-speed/barrier-sequence-pursuit': {
    term: 'jiggle peek trainer',
    anchor: 'Jiggle Peek Trainer',
    also: ['cover peeking practice', 'peekers advantage drill', 'angle holding reflex'],
  },
  '/drills/reaction-speed/fps-tracking-trainer': {
    term: 'fps tracking trainer',
    anchor: 'FPS Tracking Trainer',
    also: ['fps training', 'fps practice', 'smooth aim practice', 'strafe tracking online'],
  },
  '/drills/reaction-speed/market-doors-pursuit': {
    term: 'corner checking trainer',
    anchor: 'Corner Checking Trainer',
    also: ['angle clearing drill', 'saccadic eye training', 'slicing the pie practice'],
  },
  '/drills/reaction-speed/reaction-simulator': {
    term: 'reflex training game',
    anchor: 'Reaction Simulator Game',
    also: ['falling target intercept', 'vertical reaction drill', 'reflex game online'],
  },
  '/drills/reaction-speed/reaction-time-test': {
    term: 'reaction time test',
    anchor: 'Reaction Time Test',
    also: ['visual reflex speed test', 'reaction speed test online', 'measure reaction time in ms'],
  },
  '/drills/reaction-speed/reflex-training-drill': {
    term: 'reflex training drill',
    anchor: 'Multi-Target Reflex Drill',
    also: ['burst reflex game', 'divided attention reflex', 'reflex practice online'],
  },
  '/drills/reaction-speed/saccadic-gallery': {
    term: 'saccadic eye exercises',
    anchor: 'Saccadic Eye Exercises',
    also: ['eye jump training', 'fixation speed drill', 'eye movement exercises'],
  },
  '/drills/reaction-speed/visual-tracking-speed-test': {
    term: 'visual tracking test',
    anchor: 'Visual Tracking Speed Test',
    also: ['eye tracking speed test', 'visual tracking games online', 'hand eye tracking test'],
  },

  // ---------------- VISUAL ----------------
  '/drills/visual/depth-perception/distance-judgment': {
    term: 'depth perception test',
    anchor: 'Depth Perception Test',
    also: ['stereoscopic vision drill', 'distance judgment training', 'visual-perception drills'],
  },
  '/drills/visual/reaction-speed/go/no-go': {
    term: 'go no-go test',
    anchor: 'Go/No-Go Impulse Control Test',
    also: ['impulse control test', 'response inhibition drill', 'reaction speed test'],
  },
  '/drills/visual/reaction-speed/light-reaction': {
    term: 'visual reflex test',
    anchor: 'Light Reaction Reflex Test',
    also: ['reaction time test online', 'millisecond latency test', 'visual reaction drill'],
  },
  '/drills/visual/tracking-accuracy/moving-target': {
    term: 'moving target tracking test',
    anchor: 'Moving Target Intercept Test',
    also: ['visual pursuit tracking', 'kinetic intercept drill', 'hand-eye tracking game'],
  },
  '/drills/visual/tracking-accuracy/multiple-targets': {
    term: 'multiple object tracking test',
    anchor: 'Multiple Object Tracking Test',
    also: ['mot test', 'visual attention game', 'track multiple targets'],
  },
  '/drills/visual/tracking-accuracy/pursuit-tracker': {
    term: 'smooth pursuit test',
    anchor: 'Smooth Pursuit Test',
    also: ['visual aim training game', 'pursuit tracking drill', 'visual drill'],
  },
  '/drills/visual/visual-recognition/entropic-grid': {
    term: 'visual search test',
    anchor: 'Entropic Grid Visual Search',
    also: ['concentration grid test', 'scanning speed drill', 'visual noise filtering'],
  },
  '/drills/visual/visual-recognition/rhythm-anomaly': {
    term: 'visual timing test',
    anchor: 'Rhythm Anomaly Timing Test',
    also: ['temporal perception drill', 'beat anomaly detection', 'visual perception test'],
  },
  '/drills/visual/visual-recognition/visual-search': {
    term: 'conjunctive visual search',
    anchor: 'Conjunctive Visual Search Test',
    also: ['target scanning test', 'visual-perception drills', 'feature search drill'],
  },

  // ---------------- VISUAL TRACKING ----------------
  '/drills/visual-tracking/constant-slow-pursuit': {
    term: 'smooth pursuit eye exercise',
    anchor: 'Smooth Pursuit Eye Exercise',
    also: ['slow tracking drill', 'eye tracking training', 'gaze stability practice'],
  },
  '/drills/visual-tracking/directional-chaos-pursuit': {
    term: 'erratic motion eye drill',
    anchor: 'Erratic Motion Eye Drill',
    also: ['chaotic tracking practice', 'unpredictable target tracking', 'eye tracking training'],
  },
  '/drills/visual-tracking/dynamic-evasion-pursuit': {
    term: 'reactive eye tracking drill',
    anchor: 'Reactive Eye Tracking Drill',
    also: ['evasive target pursuit', 'reaction tracking exercise', 'visual tracking games online'],
  },
  '/drills/visual-tracking/ghosting-suppress-pursuit': {
    term: 'eye fixation stability training',
    anchor: 'Eye Fixation Stability Training',
    also: ['ghosting suppression drill', 'gaze steadiness exercise', 'visual fixation practice'],
  },
  '/drills/visual-tracking/infinity-pursuit': {
    term: 'figure-8 eye tracking exercise',
    anchor: 'Figure-8 Eye Tracking Exercise',
    also: ['infinity loop tracking', 'lazy eight eye drill', 'smooth pursuit training'],
  },
  '/drills/visual-tracking/momentum-teleport-pursuit': {
    term: 'anticipatory eye tracking drill',
    anchor: 'Anticipatory Eye Tracking Drill',
    also: ['target reacquisition practice', 'momentum prediction drill', 'saccade recovery training'],
  },
  '/drills/visual-tracking/peripheral-ping-pursuit': {
    term: 'peripheral vision training',
    anchor: 'Peripheral Vision Training Drill',
    also: ['peripheral awareness exercise', 'wide field vision drill', 'peripheral vision test'],
  },
  '/drills/visual-tracking/predictive-pursuit': {
    term: 'predictive eye tracking drill',
    anchor: 'Predictive Eye Tracking Drill',
    also: ['occlusion prediction training', 'trajectory anticipation drill', 'eye tracking accuracy'],
  },
  '/drills/visual-tracking/sine-wave-pursuit': {
    term: 'smooth pursuit eye training',
    anchor: 'Sine Wave Pursuit Training',
    also: ['wave tracking exercise', 'oscillating target drill', 'eye tracking training'],
  },
  '/drills/visual-tracking/spatial-shift-pursuit': {
    term: 'adaptive eye tracking drill',
    anchor: 'Adaptive Eye Tracking Drill',
    also: ['spatial shift exercise', 'context switching tracking', 'visual adaptation drill'],
  },
  '/drills/visual-tracking/split-screen-tracking': {
    term: 'divided attention eye test',
    anchor: 'Divided Attention Eye Test',
    also: ['dual target tracking drill', 'split screen tracking', 'attention splitting exercise'],
  },
  '/drills/visual-tracking/staircase-step': {
    term: 'vertical eye tracking exercise',
    anchor: 'Vertical Eye Tracking Exercise',
    also: ['vertical zig-zag drill', 'staircase gaze training', 'y-axis eye movement'],
  },
  '/drills/visual-tracking/strobe-prediction-pursuit': {
    term: 'strobe vision training',
    anchor: 'Strobe Vision Training Drill',
    also: ['stroboscopic training drill', 'intermittent vision practice', 'strobe prediction exercise'],
  },
  '/drills/visual-tracking/triangular-pursuit': {
    term: 'eye tracking accuracy drill',
    anchor: 'Eye Tracking Accuracy Drill',
    also: ['angular pursuit training', 'triangular path tracking', 'gaze precision exercise'],
  },
  '/drills/visual-tracking/zig-zag-path-pursuit': {
    term: 'eye tracking coordination drill',
    anchor: 'Eye Tracking Coordination Drill',
    also: ['zig-zag path tracking', 'directional change drill', 'eye hand coordination tracking'],
  },
};

export function getDrillSeo(href) {
  return DRILL_SEO[href] || null;
}
