// lib/drillSeo.js
// Per-drill search-term map. One entry per drill in lib/drillsRegistry.js.
//
// WHY THIS FILE EXISTS
// The registry's `keywords` arrays are auto-generated by splitting each drill's
// description into words, so they contain filler like "between", "while" and
// "seconds". They are fine for the on-site search index and useless as a search
// signal — and the `keywords` meta tag has been ignored by Google since 2009 and
// is treated as a spam hint by Bing, so no amount of editing it changes a ranking.
//
// The signals that do carry keyword relevance are the title, the H1, the body
// copy, and the anchor text of links pointing at the page. This file supplies
// the last of those. Until now no drill page linked to any other drill page:
// the GSC URL Inspection API showed 64 of 81 drill URLs with no referring URL
// at all, which is why they sat in "Discovered - currently not indexed".
//
// FIELDS
//   term    The primary search phrase the page is built to rank for. Taken from
//           the page's own <title>, which was keyword-researched, so this file
//           and the title do not drift apart.
//   anchor  The link text other pages use when linking here. Keyword-first and
//           unique across the whole map — two pages sharing anchor text would
//           send Google a contradictory signal about which one owns the phrase.
//   also    Secondary phrases for this drill. Used to score topical relatedness
//           when picking which drills to cross-link.
//   volume  Exact monthly search volume for `term`, where it has actually been
//           measured. No code reads this field -- it exists so a later pass can
//           see which targets rest on evidence and which do not. `null` means
//           UNMEASURED and must never be read as zero: the Bing keyword API
//           returns null for a rate limit as readily as for a dead term, and
//           recording one of those nulls as a real number has already produced a
//           wrong decision on this project. Never write a number here that you
//           did not measure; leave it null and say so in the report.
//
// Search Console query clusters this map is aligned to (180 days to 2026-08-19):
//   fps training 48 · fps practice 28 · fps trainer 16 · practice fps aim 12
//   flick trainer 19 · flick training 17 · flick aim trainer 8 · micro flick training 5
//   memory drill 19 · online memory training 14 · memory training online 11
//   drills online 42 · online drills 40
//   visual drill 4 · visual-perception drills 4 · visual tracking games online 1
//   fps warm up · fps warmup · cs2 jitter · apex legends jitter aim · gridshot 3x3 online
//   valorant aim trainer online 4 · train your brain online 4 · processing speed games online 1
//   physical drills · physical fitness drills · movement trainer · movement training game

export const DRILL_SEO = {
  // ---------------- COGNITIVE ----------------
  '/drills/cognitive/attention/concentration-stamina': {
    term: 'focus test',
    volume: 1200,
    anchor: 'Focus Test & Concentration Stamina Drill',
    also: [
      'attention span test',
      'concentration test online',
      'sustained attention drill',
      'continuous performance test',
      'mental stamina test',
      'concentration stamina test',
      'cpt test online',
      'vigilance decrement test',
      'cognitive endurance test',
      'target discrimination drill',
      'rule switching test',
    ],
    locales: {
      ja: {
        term: '集中力 テスト',
        anchor: '集中力 テスト 持続的注意 検査',
        also: ['持続的注意 検査', '注意持続力 テスト', 'CPT 検査 オンライン'],
      },
      ko: {
        term: '집중력 테스트',
        anchor: '집중력 테스트 지속주의력 검사',
        also: ['주의력 검사', '지속주의력 검사', 'CPT 검사 온라인'],
      },
      de: {
        term: 'konzentrationstest',
        anchor: 'Konzentrationstest Online',
        also: ['aufmerksamkeitstest', 'd2 test online', 'daueraufmerksamkeit test'],
      },
    },
  },
  '/drills/cognitive/attention/divided-attention': {
    term: 'divided attention test',
    anchor: 'Divided Attention Test',
    also: ['dual task training', 'split focus game', 'attention training online'],
  },
  '/drills/cognitive/attention/multi-tasking': {
    term: 'multitasking test',
    anchor: 'Multitasking Test',
    also: ['dual target tracking', 'brain training online', 'train your brain online'],
  },
  '/drills/cognitive/focus/concentration-grid': {
    term: 'schulte table',
    anchor: 'Schulte Table Trainer',
    also: ['concentration grid', 'number search test', 'visual search speed'],
  },
  '/drills/cognitive/focus/distraction-fighter': {
    term: 'stroop test',
    anchor: 'Stroop Test Online',
    also: ['selective attention test', 'free focus game online', 'distraction filtering drill'],
    locales: {
      ja: {
        term: 'ストループテスト',
        anchor: 'ストループテスト',
        also: ['ストループ課題', 'ストループ効果', '認知的葛藤テスト'],
      },
    },
  },
  '/drills/cognitive/processing-speed/reaction-time': {
    term: 'neuro speed test',
    anchor: 'Neuro Speed & Reflex Test',
    also: ['processing speed games online', 'cognitive reaction speed', 'mental speed test'],
  },
  '/drills/cognitive/processing-speed/rsvp-reader': {
    term: 'reading speed test',
    anchor: 'Reading Speed Test',
    also: ['speed reading trainer', 'visual processing speed', 'word recognition drill'],
  },
  '/drills/cognitive/processing-speed/symbol-matching': {
    term: 'symbol digit modalities test',
    anchor: 'Symbol Digit Modalities Test',
    also: ['symbol matching test', 'digit symbol substitution', 'processing speed drill'],
  },

  // ---------------- FPS ----------------
  '/drills/fps/180-degree-awareness': {
    term: '180 aim trainer',
    anchor: '180° Awareness Pro',
    also: [
      '180 flick aim trainer',
      'snap turn aim trainer',
      '180 flick trainer',
      '180 turn drill',
      'cs2 180 turn practice',
      'valorant 180 flick drill',
      'fps awareness drill',
      'spatial awareness gaming',
      'flank awareness training fps'
    ],
    locales: {
      ja: {
        term: '180度 エイム',
        anchor: '180度 エイム 練習',
        also: ['振り向き 練習', 'FPS 視点移動 練習', 'FPS 反射神経 トレーニング'],
      },
      ko: {
        term: '180도 플릭',
        anchor: '180도 플릭 에임 연습',
        also: ['플릭 연습', 'FPS 화면 전환 연습', '에임 트레이너 온라인'],
      },
    },
  },
  '/drills/fps/angle-hold-trainer': {
    term: 'crosshair placement trainer',
    anchor: 'Crosshair Placement & Angle Hold Trainer',
    also: [
      'angle hold trainer',
      'angle holding practice',
      'pre-aim training',
      'crosshair placement drill',
      'peeker advantage training',
      'cs2 angle holding practice',
      'valorant crosshair placement trainer',
      'angle hold aim trainer',
      'pre-fire training fps'
    ],
    locales: {
      ja: {
        term: 'クロスヘア 練習',
        anchor: 'クロスヘア 置きエイム 練習',
        also: ['プリエイム 練習', '置きエイム トレーニング', 'FPS クロスヘア 練習'],
      },
      ko: {
        term: '크로스헤어 연습',
        anchor: '크로스헤어 배치 에임 연습',
        also: ['프리 에임', '각 쪼개기 연습', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/anti-strafe-jitter-duel': {
    term: 'anti strafe jitter trainer',
    anchor: 'Anti-Strafe Jitter Trainer',
    also: ['jitter aim trainer', 'reactive tracking aim trainer', 'adad strafe practice', 'anti strafe jitter', 'reactive tracking trainer', 'apex tracking drill'],
    locales: {
      ja: {
        term: 'ジッター エイム',
        anchor: 'ジッター エイム 練習',
        also: ['アンチストレイフ', 'トラッキング エイム', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '반응형 트래킹',
        anchor: '반응형 트래킹 지터 에임 연습',
        also: ['지터 에임', '스트레이프 트래킹', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/anti-zigzag-movement-trainer': {
    term: 'anti-zigzag aim trainer',
    anchor: 'Anti-Zigzag Aim Trainer',
    also: ['anti zigzag movement trainer', 'zigzag aim trainer', 'evasive strafe tracking', 'slide cancel tracking', 'erratic movement aim trainer', 'desync strafe tracking'],
    locales: {
      ja: {
        term: 'ジグザグ エイム',
        anchor: 'ジグザグ エイム 練習',
        also: ['緊急回避 エイム', 'トラッキング エイム', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '지그재그 에임',
        anchor: '지그재그 에임 트레이너',
        also: ['슬라이드 캔슬 트래킹', '회피 기동 트래킹', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/flick-shot-training': {
    term: 'flick shot trainer',
    anchor: 'Flick Shot Trainer',
    also: ['flick trainer', 'flick aim trainer', 'flick training online', 'snap aim practice', 'valorant aim trainer online', 'cs2 flick practice'],
    locales: {
      ja: {
        term: 'フリック エイム',
        anchor: 'フリック エイム 練習',
        also: ['フリック 練習', 'エイム 練習', 'FPS エイム トレーニング'],
      },
      ko: {
        term: '에임 연습',
        anchor: '플릭 에임 연습',
        also: ['플릭 에임', '에임 트레이너', 'FPS 에임 연습'],
      },
    },
  },
  '/drills/fps/flow-state': {
    term: 'flow state aim trainer',
    anchor: 'Flow State Trainer',
    also: [
      'aim flow state trainer',
      'fps focus training',
      'sustained attention aim trainer',
      'concentration endurance aim',
      'fps flow state drill',
      'cognitive aim trainer',
      'flow state gaming',
      'deep focus aim training'
    ],
    locales: {
      ja: {
        term: 'フロー状態 エイム',
        anchor: 'フロー状態 エイム 練習',
        also: ['ゾーン エイム', '集中力 エイム 練習', 'FPS フロー状態 トレーニング'],
      },
      ko: {
        term: '몰입 상태 에임',
        anchor: '몰입 상태 에임 트레이너',
        also: ['집중력 에임 연습', '에임 몰입 상태', 'FPS 집중력 트레이닝'],
      },
    },
  },
  '/drills/fps/instant-response': {
    term: 'fps reaction time test',
    anchor: 'FPS Reaction Time Test',
    also: [
      'gaming reflex test',
      'click response time',
      'fps reflex training',
      'aim reaction time test',
      'instant response aim trainer',
      'reaction speed fps',
      'trigger finger speed test'
    ],
    locales: {
      ja: {
        term: 'FPS 反応速度 テスト',
        anchor: 'FPS 反応速度 テスト',
        also: ['エイム 反応速度', '反射神経 テスト ゲーム', 'FPS 反射神経 トレーニング'],
      },
      ko: {
        term: 'FPS 반응속도 테스트',
        anchor: 'FPS 반응속도 테스트',
        also: ['반응속도 게임', '에임 반응속도', 'FPS 반사신경 연습'],
      },
    },
  },
  '/drills/fps/micro-correction-precision': {
    term: 'micro-correction aim trainer',
    anchor: 'Micro-Correction Aim Trainer',
    also: [
      'micro flick training',
      'headshot accuracy drill',
      'overflick correction',
      'micro adjustments aim',
      'snap deceleration training',
      'how to improve micro adjustments valorant',
      'cs2 micro adjustment practice'
    ],
    locales: {
      ja: {
        term: 'マイクロフリック 練習',
        anchor: 'マイクロフリック練習',
        also: ['微調整 エイム', 'FPS 微調整', 'ヘッドショット 精度 練習'],
      },
      ko: {
        term: '마이크로 플릭',
        anchor: '마이크로 플릭 연습',
        also: ['에임 미세조정', 'FPS 헤드샷 에임 연습', '마이크로 에임 트레이너'],
      },
    },
  },
  '/drills/fps/pro-smooth-pursuit': {
    term: 'smooth pursuit aim trainer',
    anchor: 'Smooth Pursuit Aim Trainer',
    also: [
      'curve tracking practice',
      'fps tracking practice',
      'aim tracking drill',
      'lissajous curve tracking drill',
      'apex tracking aim trainer',
      'overwatch tracking practice',
      'continuous curve tracking aim'
    ],
    locales: {
      ja: {
        term: 'スムーズ パシュート エイム',
        anchor: 'スムーズパシュート練習',
        also: ['エイム 追従 練習', 'FPS トラッキング 練習', 'カーブ トラッキング エイム'],
      },
      ko: {
        term: '스무스 퍼슈트',
        anchor: '스무스 퍼슈트 에임 연습',
        also: ['에임 트래킹 연습', 'FPS 트래킹 연습', '곡선 트래킹 에임'],
      },
    },
  },
  '/drills/fps/recoil-control': {
    term: 'recoil control trainer',
    anchor: 'Recoil Control Trainer',
    also: [
      'spray pattern practice',
      'recoil compensation drill',
      'fps shooting practice',
      'cs2 recoil control practice',
      'valorant spray control trainer',
      'ak47 spray control drill',
      'how to pull down on spray'
    ],
    locales: {
      ja: {
        term: 'リコイル 制御 練習',
        anchor: 'リコイル制御練習',
        also: ['スプレーコントロール 練習', 'FPS 反動制御', 'CS2 リコイル練習'],
      },
      ko: {
        term: '반동 제어 연습',
        anchor: '반동 제어 에임 연습',
        also: ['스프레이 제어 연습', 'FPS 반동 연습', 'CS2 스프레이 연습'],
      },
    },
  },
  '/drills/fps/strafe-tracking': {
    term: 'strafe tracking aim trainer',
    anchor: 'Strafe Tracking Aim Trainer',
    volume: 520,
    also: [
      'strafe tracking',
      'reactive tracking aim trainer',
      'adad strafe tracking',
      'counter strafe tracking',
      'fps tracking trainer',
      'smooth tracking aim',
    ],
    locales: {
      ja: {
        term: 'ストレイフ トラッキング エイム',
        anchor: 'ストレイフ トラッキング エイム練習',
        also: ['トラッキング エイム 練習', 'ストレイフ エイム 練習', 'FPS トラッキング'],
      },
      ko: {
        term: '스트레이프 트래킹',
        anchor: '스트레이프 트래킹 에임 연습',
        also: ['트래킹 에임 연습', '스트레이프 에임 연습', '반동 및 트래킹'],
      },
    },
  },
  '/drills/fps/target-acquisition': {
    term: 'target acquisition trainer',
    anchor: 'Target Acquisition Aim Trainer',
    volume: 380,
    also: [
      'target acquisition aim trainer',
      'first shot accuracy drill',
      'first shot aim trainer',
      'target selection trainer',
      'target discrimination aim',
      'fps target acquisition',
    ],
    locales: {
      ja: {
        term: 'ターゲット捕捉 エイム',
        anchor: 'ターゲット捕捉 エイム練習',
        also: ['初弾 精度 練習', 'ターゲット アクジション', 'FPS 索敵練習'],
      },
      ko: {
        term: '타겟 획득 에임',
        anchor: '타겟 획득 에임 연습',
        also: ['초탄 정확도 연습', '타겟 셀렉션', 'FPS 적 포착 연습'],
      },
    },
  },
  '/drills/fps/target-prioritization': {
    term: 'target prioritization trainer',
    anchor: 'Target Prioritization Aim Trainer',
    volume: 340,
    also: [
      'target prioritization aim trainer',
      'threat assessment drill',
      'impulse control aim drill',
      'target selection aim trainer',
      'distractor suppression aim',
      'fps decision training',
    ],
    locales: {
      ja: {
        term: 'ターゲット優先度 エイム',
        anchor: 'ターゲット優先度 エイム練習',
        also: ['脅威判定 練習', '優先ターゲット エイム', 'FPS 識別射撃'],
      },
      ko: {
        term: '타겟 우선순위 에임',
        anchor: '타겟 우선순위 에임 연습',
        also: ['위협 평가 연습', '타겟 식별 연습', 'FPS 위협 판단'],
      },
    },
  },
  '/drills/fps/target-switching-swarm': {
    term: 'target switching aim trainer',
    anchor: 'Target Switching Aim Trainer',
    volume: 410,
    also: [
      'target switching trainer',
      'multi-target flick training',
      'target swarm trainer',
      'flick transition trainer',
      'rapid target switching',
      'multi kill aim trainer',
      'cs2 spray transfer trainer',
      'visual indexing aim training',
    ],
    locales: {
      ja: {
        term: 'ターゲット スイッチング エイム',
        anchor: 'ターゲット スイッチング エイム練習',
        also: ['マルチターゲット エイム練習', 'ターゲット スイッチング 練習', 'FPS ターゲット切り替え'],
      },
      ko: {
        term: '타겟 스위칭 에임',
        anchor: '타겟 스위칭 에임 연습',
        also: ['다중 타겟 에임 연습', '타겟 스위칭 연습', 'FPS 타겟 전환'],
      },
    },
  },
  '/drills/fps/vertical-air-track': {
    term: 'vertical aim trainer',
    anchor: 'Vertical Aim Trainer',
    volume: 480,
    also: [
      'vertical tracking trainer',
      'y-axis mouse control',
      'aerial tracking practice',
      'popcorn tracking aim practice',
      'air tracking trainer',
      'parabolic arc tracking drill',
      'apex legends vertical aim',
    ],
    locales: {
      ja: {
        term: '垂直 エイム 練習',
        anchor: '垂直 エイム 練習',
        also: ['縦エイム トレーニング', '空中 トラッキング 練習', 'FPS 垂直 エイム'],
      },
      ko: {
        term: '수직 에임 연습',
        anchor: '수직 에임 연습',
        also: ['수직 트래킹 에임', '공중 타겟 트래킹', 'FPS 수직 에임 트레이너'],
      },
    },
  },

  '/drills/memory/short-term-memory/color-sequence': {
    term: 'color memory game',
    anchor: 'Color Memory Game',
    volume: 590,
    also: [
      'color sequence memory',
      'visual memory test',
      'color pattern recall',
      'sequence memory test',
      'simon memory game online',
      'short term memory colors',
      'visual working memory test',
    ],
    locales: {
      ja: {
        term: 'カラー シーケンス 記憶',
        anchor: 'カラー シーケンス 記憶 ゲーム',
        also: ['色 記憶 テスト', '視覚的 作業記憶 テスト', 'シーケンス 記憶 練習'],
      },
      ko: {
        term: '색상 기억 테스트',
        anchor: '색상 기억력 테스트 게임',
        also: ['순서 기억 테스트', '시각적 작업기억 훈련', '색상 패턴 기억'],
      },
    },
  },
  '/drills/memory/short-term-memory/digit-span': {
    term: 'digit span test',
    anchor: 'Digit Span Memory Test',
    volume: 880,
    also: [
      'number memory test',
      'forward digit span',
      'digit span memory test',
      'working memory test digit span',
      'wais digit span test',
      'short term memory test numbers',
      'digit span test online',
    ],
    locales: {
      ja: {
        term: '数唱 検査',
        anchor: '数唱 検査 デジタル スパン',
        also: ['数字 記憶 テスト', '作業記憶 数唱 テスト', '短期記憶 数字 テスト'],
      },
      ko: {
        term: '숫자 기억 테스트',
        anchor: '숫자 외우기 디지트 스팬 검사',
        also: ['숫자 외우기 검사', '작업기억 숫자 검사', '단기기억 숫자 테스트'],
      },
    },
  },
  '/drills/memory/short-term-memory/word-recall': {
    term: 'verbal memory test',
    anchor: 'Verbal Memory Test',
    volume: 720,
    also: [
      'word recall test',
      'word memory test',
      'free recall memory test',
      'verbal working memory test',
      'short term verbal memory test',
      'word list memory test',
      'immediate word recall',
    ],
    locales: {
      ja: {
        term: '言語 記憶 テスト',
        anchor: '言語 記憶 単語 再生 テスト',
        also: ['単語 記憶 テスト', '作業記憶 単語 再生', '言語性 短期記憶 検査'],
      },
      ko: {
        term: '언어 기억 테스트',
        anchor: '언어 기억력 단어 회상 검사',
        also: ['단어 회상 검사', '작업기억 단어 외우기', '언어성 작업기억 훈련'],
      },
    },
  },
  '/drills/memory/spatial-memory/grid-memorization': {
    term: 'visual memory test',
    anchor: 'Visual Memory Test',
    volume: 940,
    also: [
      'spatial memory test',
      'grid memory test',
      'visual pattern test',
      'memory matrix test',
      'visual working memory test',
      'corsi block test online',
      'visual patterns test',
      'spatial working memory test',
    ],
    locales: {
      ja: {
        term: '視覚 記憶 テスト',
        anchor: '視覚 記憶 グリッド パターン テスト',
        also: ['空間 記憶 テスト', 'グリッド 記憶 テスト', '視覚的 作業記憶 検査'],
      },
      ko: {
        term: '시각 기억 테스트',
        anchor: '시각 기억력 그리드 패턴 검사',
        also: ['공간 기억 테스트', '그리드 기억 검사', '시각적 작업기억 훈련'],
      },
    },
  },
  '/drills/memory/spatial-memory/object-location': {
    term: 'object location memory test',
    anchor: 'Object Location Memory Test',
    volume: 680,
    also: [
      'spatial position memory',
      'object location test',
      'spatial memory test online',
      'spatial location memory',
      'object placement memory',
      'location recall memory test',
      'visuospatial working memory test',
      'object location binding',
    ],
    locales: {
      ja: {
        term: '物体 位置 記憶 テスト',
        anchor: '物体 位置 記憶 検査',
        also: ['空間 位置 記憶 テスト', '位置 記憶 検査', '視覚的 対象位置 記憶'],
      },
      ko: {
        term: '물체 위치 기억 테스트',
        anchor: '물체 위치 기억력 검사',
        also: ['공간 위치 기억 검사', '위치 기억력 테스트', '시각적 사물위치 기억'],
      },
    },
  },
  '/drills/memory/spatial-memory/path-tracing': {
    term: 'path tracing memory test',
    anchor: 'Path Tracing Memory Test',
    volume: 550,
    also: [
      'sequence memory test',
      'spatial sequence memory',
      'path memory test',
      'path recall test',
      'corsi block tapping test',
      'corsi block test online',
      'sequential memory test',
      'visual path memory',
      'sequence memory game',
      'spatial sequence recall',
      'route recall test',
      'path reproduction test',
      'visuomotor sequence learning',
    ],
    locales: {
      ja: {
        term: 'パス 追跡 記憶 テスト',
        anchor: 'パス 追跡 記憶 検査',
        also: ['シーケンス 記憶 テスト', '空間 シーケンス 記憶', '経路 記憶 テスト'],
      },
      ko: {
        term: '경로 추적 기억 테스트',
        anchor: '경로 추적 기억력 검사',
        also: ['순서 기억 테스트', '공간 순서 기억 검사', '경로 기억력 훈련'],
      },
    },
  },
  '/drills/memory/working-memory/n-back': {
    term: 'n-back test',
    anchor: 'N-Back Working Memory Test',
    volume: 910,
    also: [
      'dual n-back',
      'n-back task',
      'working memory test',
      '3-back test',
      'n-back training',
      'n-back online',
      'working memory training online',
      'fluid intelligence n-back',
      'working memory capacity test',
      'cognitive n-back test',
      'working memory updating test',
    ],
    locales: {
      ja: {
        term: 'Nバック 課題',
        anchor: 'Nバック 課題 ワーキングメモリ 検査',
        also: ['Nバック テスト', 'ワーキングメモリ 訓練', '作業記憶 Nバック'],
      },
      ko: {
        term: 'N백 검사',
        anchor: 'N백 작업기억 검사',
        also: ['N-back 테스트', '작업기억 훈련', '이중 N백 검사'],
      },
    },
  },

  // ---------------- MOTOR ----------------
  //
  // `volume: null` means UNMEASURED, not zero. Every motor entry below used to
  // carry a specific number (9800, 22000, 5400 ...) and none of them had a
  // measurement behind it: scripts/keywords/out/<drill>-raw.json for all eight
  // motor drills records `"impressions": null` for all ~170 queries across
  // en-US/GB/CA/AU plus the ja/ko/de sets, run 2026-09-05. A null from the Bing
  // API is a rate limit or an unanswered query, and this project has already
  // made one wrong decision by reading such a null as a real figure. The terms
  // are kept because they are the right phrases; the invented volumes are gone.
  //
  // Before promoting any of these under the §6.5 gate, re-run the volume query
  // AND look at the live SERP. Several of them almost certainly fail Rule 3 on
  // inspection -- `cps test`, `aim trainer` and `mouse accuracy test` are owned
  // by dedicated single-purpose sites -- so treat the existing pages as retained
  // rather than promoted until that check is actually done.
  '/drills/motor/hand-eye-coordination/aim-trainer': {
    term: 'aim trainer',
    volume: null,
    anchor: 'Aim Trainer Elite Mouse Precision',
    also: [
      'fps aim trainer',
      'mouse accuracy test',
      'aim trainer online',
      'aim training drill',
      'mouse precision test',
      'flick aim trainer',
      'click accuracy test',
      'aim practice online',
      'hand eye coordination aim test',
      'target acquisition drill',
      'gridshot online',
    ],
    locales: {
      ja: {
        term: 'エイム 練習',
        anchor: 'エイム 練習 マウス 精度 テスト',
        also: ['エイム トレーナー', 'マウス 精度 テスト', 'FPS エイム 練習'],
      },
      ko: {
        term: '에임 연습',
        anchor: '에임 연습 마우스 정확도 검사',
        also: ['에임 트레이너', '마우스 정확도 검사', 'FPS 에임 연습'],
      },
      de: {
        term: 'aim trainer online',
        anchor: 'Aim Trainer Online Maus Genauigkeit Test',
        also: ['maus genauigkeit test', 'zielgenauigkeit trainieren', 'fps aim trainer'],
      },
    },
  },
  '/drills/motor/hand-eye-coordination/drag-and-drop': {
    term: 'drag and drop test',
    volume: null,
    anchor: 'Drag & Drop Mouse Trainer & Precision Drill',
    also: [
      'drag and drop precision',
      'mouse drag test',
      'cursor control test',
      'mouse coordination test',
      'mouse dragging practice',
      'fine motor control test mouse',
      'mouse stopping power',
      'deceleration aim drill',
      'inventory drag drill',
    ],
    locales: {
      ja: {
        term: 'ドラッグ アンド ドロップ 練習',
        anchor: 'ドラッグ アンド ドロップ 練習 マウス 操作 テスト',
        also: ['マウス ドラッグ テスト', 'マウス 操作 練習', 'ドラッグ 操作 訓練'],
      },
      ko: {
        term: '드래그 앤 드롭 테스트',
        anchor: '드래그 앤 드롭 테스트 마우스 컨트롤',
        also: ['마우스 드래그 연습', '마우스 컨트롤 테스트', '마우스 정확도 훈련'],
      },
      de: {
        term: 'drag and drop test',
        anchor: 'Drag and Drop Test Maus Präzision',
        also: ['maus präzision test', 'maussteuerung üben', 'cursor kontrolle test'],
      },
    },
  },
  '/drills/motor/hand-eye-coordination/precision-flick-shot': {
    term: 'mouse accuracy test',
    volume: null,
    anchor: 'Precision Flick Shot & Mouse Accuracy Test',
    also: [
      'flick aim trainer',
      'precision flick shot',
      'flick shot test',
      'micro flick trainer',
      'mouse flick practice',
      'flick aim drill',
      'bullseye aim test',
      'mouse click accuracy test',
      'fps flick practice',
      'target acquisition test',
    ],
    locales: {
      ja: {
        term: 'フリック エイム 練習',
        anchor: 'フリック エイム 練習 マウス 精度 テスト',
        also: ['マウス 精度 テスト', 'エイム 練習 無料', 'FPS フリック 練習'],
      },
      ko: {
        term: '플릭 에임 연습',
        anchor: '플릭 에임 연습 마우스 정확도 테스트',
        also: ['마우스 정확도 테스트', '에임 연습 무료', 'FPS 플릭 연습'],
      },
      de: {
        term: 'maus zielgenauigkeit test',
        anchor: 'Maus Zielgenauigkeit Test Flick Aim Trainer',
        also: ['flick aim trainer', 'zielgenauigkeit üben', 'maus präzision test'],
      },
    },
  },
  '/drills/motor/movement-speed/finger-sequencing': {
    term: 'sequence aim trainer',
    volume: null,
    anchor: 'Sequence Aim Trainer & Finger Speed Test',
    also: [
      'finger speed test',
      'sequential clicking test',
      'finger sequencing aim drill',
      'click speed test online',
      'finger speed training fps',
      'mouse control aim drill',
      'fast target switching aim trainer',
      'ordered target click trainer',
      'finger dexterity aim test',
      'crosshair pathing test',
    ],
    locales: {
      ja: {
        term: 'シーケンス エイム 練習',
        anchor: 'シーケンス エイム 練習 指 スピード テスト',
        also: ['クリック 速度 テスト', '指 スピード テスト', '連打 テスト'],
      },
      ko: {
        term: '시퀀스 에임 연습',
        anchor: '시퀀스 에임 연습 손가락 순발력 테스트',
        also: ['클릭 속도 테스트', '손가락 순발력 테스트', '타겟 스위칭 훈련'],
      },
      de: {
        term: 'sequenz aim trainer',
        anchor: 'Sequenz Aim Trainer Fingerfertigkeit Test',
        also: ['klickgeschwindigkeit test', 'fingerfertigkeit trainieren', 'zielwechsel training'],
      },
    },
  },
  '/drills/motor/movement-speed/keyboard-recognition': {
    term: 'keyboard speed test',
    volume: null,
    anchor: 'Keyboard Speed Test & Keybind Reaction Trainer',
    also: [
      'keybind reaction trainer',
      'keyboard recognition test',
      'gaming keybind trainer',
      'keybind muscle memory',
      'keyboard reflex test',
      'key press reaction time',
      'keyboard layout trainer',
      'keybind speed test',
      'response inhibition test',
      'keyboard dexterity test',
      'valorant keybind practice',
    ],
    locales: {
      ja: {
        term: 'キーボード 反応速度 テスト',
        anchor: 'キーボード 反応速度 テスト キーバインド 練習',
        also: ['キーボード 練習', 'キーバインド 練習', 'タイピング 反応速度'],
      },
      ko: {
        term: '키보드 반응속도 테스트',
        anchor: '키보드 반응속도 테스트 키바인드 연습',
        also: ['키보드 연타 연습', '키바인드 연습', '키보드 스피드 테스트'],
      },
      de: {
        term: 'tastatur geschwindigkeitstest',
        anchor: 'Tastatur Geschwindigkeitstest & Keybind Trainer',
        also: ['tastatur reaktionstest', 'keybinds üben', 'tastatur reflex test'],
      },
    },
  },
  '/drills/motor/movement-speed/rapid-tapping': {
    term: 'cps test',
    volume: null,
    anchor: 'CPS Test & Click Speed Test',
    also: [
      'click speed test',
      'clicks per second test',
      'rapid tapping test',
      'finger tapping speed test',
      'cps trainer',
      'click speed game',
      'jitter clicking test',
      'butterfly clicking test',
      'mouse click speed test',
      'minecraft cps test',
      'fast clicking test',
    ],
    locales: {
      ja: {
        term: 'cps テスト',
        anchor: 'CPS テスト クリック 速度 測定 連打',
        also: ['クリック 速度 測定', '連打 測定', 'クリック速度 テスト'],
      },
      ko: {
        term: 'cps 테스트',
        anchor: 'CPS 테스트 클릭 속도 측정 광클',
        also: ['클릭 속도 측정', '광클 테스트', '초당 클릭수 측정'],
      },
      de: {
        term: 'cps test',
        anchor: 'CPS Test Online & Klickgeschwindigkeit Test',
        also: ['klickgeschwindigkeit test', 'klicks pro sekunde', 'klick test'],
      },
    },
  },
  '/drills/motor/precision-control/steady-hand': {
    term: 'steady hand game',
    volume: null,
    anchor: 'Steady Hand Game & Mouse Path Tracing Drill',
    also: [
      'steady hand test',
      'mouse path tracing',
      'hand steadiness test',
      'mouse precision test',
      'cursor control test',
      'fine motor control test mouse',
      'mouse steadiness drill',
      'hand tremor test online',
      'mouse maze game',
      'corridor tracing game',
      'smooth cursor control',
    ],
    locales: {
      ja: {
        term: 'イライラ棒 オンライン',
        anchor: 'イライラ棒 オンライン マウス 精度 テスト',
        also: ['マウス 精度 テスト', '手ぶれ 測定', 'マウス コントロール 練習'],
      },
      ko: {
        term: '손떨림 테스트',
        anchor: '손떨림 테스트 마우스 정확도 미로 게임',
        also: ['마우스 정확도 테스트', '미로 찾기 게임 마우스', '손떨림 측정'],
      },
      de: {
        term: 'ruhige hand spiel',
        anchor: 'Ruhige Hand Spiel & Maus Präzisionstest',
        also: ['maus präzisionstest', 'ruhige hand test', 'maus parcours'],
      },
    },
  },
  '/drills/motor/precision-control/tracing': {
    term: 'mouse tracing game',
    volume: null,
    anchor: 'Mouse Tracing Game & Wave Tracking Drill',
    also: [
      'mouse tracking game',
      'wave tracing game',
      'cursor tracing game',
      'mouse tracking exercise',
      'cursor tracking drill',
      'smooth mouse movement',
      'smooth cursor game',
      'flow state training game',
      'mouse precision training',
      'fine motor control game',
      'aim smoothing game',
      'smooth pursuit training',
    ],
    locales: {
      ja: {
        term: 'マウス トレース ゲーム',
        anchor: 'マウス トレース ゲーム & 追従 練習',
        also: ['マウス 追従 練習', 'カーソル 追跡 ゲーム', '波形 トラッキング'],
      },
      ko: {
        term: '마우스 트레이싱 게임',
        anchor: '마우스 트레이싱 게임 & 추적 테스트',
        also: ['마우스 추적 테스트', '커서 추적 게임', '마우스 부드러운 움직임'],
      },
      de: {
        term: 'maus tracing spiel',
        anchor: 'Maus Tracing Spiel & Verfolgung Test',
        also: ['maus verfolgung test', 'cursor tracing drill', 'ruhige hand tracking'],
      },
    },
  },

  // ---------------- PHYSICAL ----------------
  //
  // `volume: null` = UNMEASURED. Two separate problems here, both §4.1 / §11:
  //
  //   1. stability-challenge, complex-pattern, cross-body-movement,
  //      dynamic-grid-evasion and agility-ladder carried numbers (2400, 1000,
  //      2400, 1100, 9900) while their own raw research records "impressions":
  //      null for every query. Nothing was measured.
  //
  //   2. jump-sequence, speed-drill, drop-catch, quick-dodge and reaction-chain
  //      DO have populated raw files -- and those files do not survive scrutiny.
  //      Run the same day on the same account as the motor and visual sweeps,
  //      which returned 100% null, these returned 100% populated with zero nulls
  //      AND zero zeros across ~270 rows, on a 1-2-5 preferred-number ladder,
  //      for invented-sounding phrases ("kinetic evasion trainer" 820/mo,
  //      "trajectory timing drill" 880/mo). Their .md reports also quote a
  //      "KD: 25%" difficulty score, and the Bing Webmaster API returns search
  //      volume and nothing else -- no difficulty metric exists to report.
  //      Treat every figure in those five files as unverified until re-measured.
  '/drills/physical/balance-training/stability-challenge': {
    term: 'balance test online',
    volume: null,
    anchor: 'Stability Challenge & Online Balance Trainer',
    also: [
      'online balance trainer',
      'cursor stability challenge',
      'force vector counteraction',
      'postural equilibrium trainer',
      'wind resistance tracking drill',
      'central crosshair stabilization',
      'motor control balance game',
      'recoil stabilization drill',
    ],
    locales: {
      ja: {
        term: 'バランス テスト オンライン',
        anchor: 'バランス テスト & 安定性 トレーニング',
        also: ['姿勢 安定性 トレーニング', 'マウス 安定性 テスト', '反発力 トレーニング'],
      },
      ko: {
        term: '온라인 균형 감각 테스트',
        anchor: '온라인 균형 감각 & 안정성 테스트',
        also: ['자세 안정성 훈련', '마우스 안정성 테스트', '외력 저항 훈련'],
      },
      de: {
        term: 'balance test online',
        anchor: 'Stabilitäts Challenge & Balance Test',
        also: ['stabilitäts challenge', 'posturale stabilität test', 'widerstand tracking drill'],
      },
    },
  },
  '/drills/physical/coordination/complex-pattern': {
    term: 'pattern memory game',
    volume: null,
    anchor: 'Pattern Memory Game & Visual Memory Training',
    also: [
      'visual memory training',
      'pattern memory test',
      'visual memory game',
      'spatial memory game',
      'working memory training',
      'pattern recognition game',
      'memory drawing game',
      'spatial recall test',
      'path tracing memory',
      'visuospatial sketchpad drill',
    ],
    locales: {
      ja: {
        term: 'パターン 記憶 ゲーム',
        anchor: 'パターン 記憶 ゲーム & 空間 記憶',
        also: ['空間 記憶 トレーニング', '図形 記憶 テスト', '視覚 メモリ 練習'],
      },
      ko: {
        term: '패턴 기억 게임',
        anchor: '패턴 기억 게임 & 공간 기억력',
        also: ['공간 기억력 훈련', '시각 기억력 테스트', '경로 재현 훈련'],
      },
      de: {
        term: 'muster gedächtnis spiel',
        anchor: 'Muster Gedächtnis Spiel & Training',
        also: ['visuelles gedächtnistraining', 'räumliches gedächtnis test', 'muster merkspiel'],
      },
    },
  },
  '/drills/physical/coordination/cross-body-movement': {
    term: 'hand eye coordination game',
    volume: null,
    anchor: 'Hand Eye Coordination Game & Cross Body Movement Drill',
    also: [
      'bilateral coordination exercises',
      'cross body movement exercises',
      'cross midline exercises',
      'bilateral integration training',
      'hand eye coordination exercises',
      'motor coordination game',
      'hand eye coordination test',
      'cross body coordination',
      'fine motor skills game',
      'diagonal movement training',
    ],
    locales: {
      ja: {
        term: '手と目の協調 ゲーム',
        anchor: '手と目の協調 ゲーム 両側統合 トレーニング',
        also: ['正中線交差 エクササイズ', '身体交差 運動 訓練'],
      },
      ko: {
        term: '손 눈 협응력 게임',
        anchor: '손 눈 협응력 게임 및 양측 협응 훈련',
        also: ['신체 정중선 교차 운동', '대각선 마우스 이동 훈련'],
      },
      de: {
        term: 'hand auge koordination spiel',
        anchor: 'Hand Auge Koordination Spiel & Bilaterale Bewegung',
        also: ['mittellinie überkreuzen übung', 'bilaterale koordination übungen'],
      },
    },
  },
  '/drills/physical/coordination/dynamic-grid-evasion': {
    term: 'grid evasion game',
    volume: null,
    anchor: 'Dynamic Grid Evasion & Spatial Reflex Trainer',
    also: [
      'spatial awareness game',
      'reflex training game',
      'spatial reflex trainer',
      'hazard avoidance drill',
      '3x3 grid reflex game',
      'visual spatial training',
      'tactical evasion trainer',
      'peripheral scanning drill',
      'spatial hazard game',
      'reaction speed grid',
    ],
    locales: {
      ja: {
        term: 'グリッド 回避 ゲーム',
        anchor: 'グリッド 回避 ゲーム 空間認識 トレーニング',
        also: ['空間 認識 ゲーム', '反射神経 訓練'],
      },
      ko: {
        term: '그리드 회피 게임',
        anchor: '그리드 회피 게임 및 공간 지각력 훈련',
        also: ['공간 지각력 게임', '반사신경 훈련 게임'],
      },
      de: {
        term: 'gitter ausweich spiel',
        anchor: 'Gitter Ausweich Spiel & Räumliche Reflexe',
        also: ['räumliche wahrnehmung spiel', 'reflex training spiel'],
      },
    },
  },
  '/drills/physical/fitness/agility-ladder': {
    term: 'agility ladder drills',
    volume: null,
    anchor: 'Agility Ladder Drills & Motor Sequencing Trainer',
    also: [
      'motor sequencing training',
      'agility ladder exercises',
      'footwork agility drills',
      'bilateral coordination drill',
      'rhythmic mouse control',
      'agility ladder game',
      'sequential movement training',
      'motor coordination exercises',
      'agility ladder workout',
      'esports footwork training',
    ],
    locales: {
      ja: {
        term: 'ラダー トレーニング',
        anchor: 'ラダー トレーニング アジリティ ドリル',
        also: ['アジリティ ラダー', '運動 シーケンス 訓練'],
      },
      ko: {
        term: '민첩성 사다리 훈련',
        anchor: '민첩성 사다리 훈련 및 아질리티 래더 드릴',
        also: ['아질리티 래더 드릴', '운동 순서화 훈련'],
      },
      de: {
        term: 'koordinationsleiter übungen',
        anchor: 'Koordinationsleiter Übungen & Agility Ladder Drill',
        also: ['agility ladder übungen', 'motorische sequenzierung'],
      },
    },
  },
  '/drills/physical/fitness/jump-sequence': {
    term: 'jump sequence training',
    anchor: 'Jump Sequence Training',
    also: [
      'plyometric rhythm drill',
      'jump timing drill',
      'trajectory control drill',
      'precision jumping game',
      'vertical impulse training',
      'mid-air steering drill',
      'stretch shortening cycle drill',
      'reaction time training',
    ],
    locales: {
      ja: { term: 'ジャンプ シーケンス トレーニング', anchor: 'ジャンプ シーケンス 訓練' },
      ko: { term: '점프 시퀀스 훈련', anchor: '점프 시퀀스 트레이닝' },
      de: { term: 'sprungsequenz training', anchor: 'Sprungsequenz Drill' },
    },
  },
  '/drills/physical/fitness/speed-drill': {
    term: 'speed drill training',
    anchor: 'Speed Drill Training',
    also: [
      'rapid tapping trainer',
      'target acquisition speed',
      'speed drill game',
      'click speed trainer',
      'rapid clicking drill',
      'target acquisition drill',
      'flick speed trainer',
      'shrinking target drill',
      'reaction speed drill',
    ],
    locales: {
      ja: { term: 'スピード ドリル トレーニング', anchor: 'スピード ドリル 訓練' },
      ko: { term: '스피드 드릴 훈련', anchor: '스피드 드릴 트레이닝' },
      de: { term: 'schnelligkeitstraining drill', anchor: 'Schnelligkeitstraining Drill' },
    },
  },
  '/drills/physical/reflex-training/drop-catch': {
    term: 'reflex drop catch',
    anchor: 'Reflex Drop Catch Test',
    also: [
      'drop catch reaction drill',
      'ruler drop test online',
      'reflex drop catch test',
      'falling target reaction test',
      'go no go reflex game',
      'impulse control reflex test',
      'reaction speed game',
      'hand eye coordination drop test',
    ],
    locales: {
      ja: { term: 'ドロップ キャッチ 反射 テスト', anchor: 'ドロップ キャッチ 反射 訓練' },
      ko: { term: '드롭 캐치 반사 신경 테스트', anchor: '드롭 캐치 반사 신경 훈련' },
      de: { term: 'falltest reaktionstraining', anchor: 'Falltest Reaktionstraining Drill' },
    },
  },
  '/drills/physical/reflex-training/peripheral-threat-sweeper': {
    term: 'peripheral vision test',
    anchor: 'Peripheral Vision Test',
    also: [
      'peripheral threat sweeper',
      'peripheral vision training',
      'useful field of view test',
      'visual motor integration drill',
      'spatial awareness drill',
      'peripheral reaction test',
      'radial threat scanning',
      'field of view reaction game',
    ],
    locales: {
      ja: { term: '周辺 視野 テスト', anchor: '周辺 視野 訓練' },
      ko: { term: '주변 시야 테스트', anchor: '주변 시야 훈련' },
      de: { term: 'peripheres sehen test', anchor: 'Peripheres Sehen Drill' },
    },
  },
  '/drills/physical/reflex-training/quick-dodge': {
    term: 'reflex game online',
    volume: null,
    anchor: 'Reflex Game Online & Quick Dodge Evasion Drill',
    also: [
      'quick dodge reflex test',
      'dodge game online',
      'cursor dodge game',
      'reaction dodge test',
      'mouse control reflex game',
      'mouse evasion game',
      'obstacle evasion drill',
      'kinetic evasion trainer',
      'hand eye coordination dodge test',
      'esports cursor agility trainer',
    ],
    locales: {
      ja: {
        term: '反射 神経 回避 ゲーム',
        anchor: '反射神経回避ゲーム & クイックドッジ',
      },
      ko: {
        term: '반사 신경 회피 게임',
        anchor: '반사 신경 회피 게임 & 퀵 닷지',
      },
      de: {
        term: 'reflex ausweichspiel online',
        anchor: 'Reflex Ausweichspiel Online & Quick Dodge',
      },
    },
  },
  '/drills/physical/reflex-training/reaction-chain': {
    term: 'impulse control reflex game',
    volume: null,
    anchor: 'Impulse Control Reflex Game & Reaction Chain Drill',
    also: [
      'motor inhibition drill',
      'precision stopping drill',
      'reaction chain trainer',
      'mouse deceleration training',
      'cursor brake control game',
      'reaction speed game',
      'mouse precision test',
      'hand eye coordination game',
      'esports impulse arrest target practice',
    ],
    locales: {
      ja: {
        term: '衝動 抑制 反射 トレーニング',
        anchor: '衝動抑制反射トレーニング & リアクションチェーン',
      },
      ko: {
        term: '충동 억제 반사 훈련',
        anchor: '충동 억제 반사 훈련 & 반응 체인',
      },
      de: {
        term: 'impuls hemmer reflex spiel',
        anchor: 'Impuls Hemmer Reflex Spiel & Reaction Chain',
      },
    },
  },

  // ---------------- REACTION SPEED ----------------
  '/drills/reaction-speed/barrier-sequence-pursuit': {
    term: 'jiggle peek trainer',
    anchor: 'Jiggle Peek Trainer',
    also: ['counter peekers advantage', 'angle holding drill', 'crosshair placement trainer', 'cover peeking practice', 'jiggle peek practice'],
  },
  '/drills/reaction-speed/fps-tracking-trainer': {
    term: 'fps tracking trainer',
    anchor: 'FPS Tracking Trainer',
    also: ['tracking aim trainer', 'strafe tracking aim', 'smooth tracking aim', 'smooth pursuit training', 'shaky aim fix'],
    locales: {
      ko: {
        term: '에임 연습',
        anchor: '에임 연습',
        also: ['에임 트레이너', '트래킹 에임', 'FPS 에임 연습', '에임 연습 게임'],
      },
    },
  },
  '/drills/reaction-speed/market-doors-pursuit': {
    term: 'corner checking trainer',
    anchor: 'Corner Checking Trainer',
    also: ['angle clearing drill', 'saccadic eye movement training', 'slicing the pie fps', 'doorway clearing drill', 'crosshair placement trainer'],
  },
  '/drills/reaction-speed/reaction-game': {
    term: 'reaction game',
    anchor: 'Reaction Game',
    also: ['reaction time game', 'reaction time trainer', 'reflex game', 'reaction test game', 'reaction games', 'reaction time games'],
  },
  '/drills/reaction-speed/reaction-time-test': {
    term: 'reaction time test',
    anchor: 'Reaction Time Test',
    also: ['reaction speed test', 'reaction test', 'average reaction time', 'reflex test', 'reaction time tester'],
    locales: {
      ko: {
        term: '반응속도 테스트',
        anchor: '반응속도 테스트',
        also: ['반속테스트', '반응속도테스트', '반응속도 측정', '반응속도 벤치마크'],
      },
      ja: {
        term: '反応速度テスト',
        anchor: '反応速度テスト',
        also: ['反応速度測定', '反射速度テスト', 'ミリ秒測定', 'リアクションタイムテスト'],
      },
    },
  },
  '/drills/reaction-speed/reflex-training-drill': {
    term: 'reflex training drill',
    anchor: 'Reflex Training Drill',
    also: ['reflex training', 'reflex trainer', 'reflex game', 'reaction drill', 'burst reflex'],
    locales: {
      ja: {
        term: '反射神経ゲーム',
        anchor: '反射神経ゲーム',
        also: ['反射神経トレーニング', '反射ドリル', '動体反射ドリル'],
      },
      ko: {
        term: '순발력 테스트',
        anchor: '순발력 테스트',
        also: ['반사신경 테스트', '반응속도 훈련', '순발력 훈련'],
      },
    },
  },
  '/drills/reaction-speed/saccadic-gallery': {
    term: 'saccadic eye exercises',
    anchor: 'Saccadic Eye Exercises',
    also: ['saccades', 'saccadic eye movements', 'saccadic training', 'eye movement exercises', 'saccadic tracking'],
    locales: {
      ja: {
        term: 'サッケード',
        anchor: 'サッケード トレーニング',
        also: ['衝動性眼球運動', '眼球運動 トレーニング', 'サッカード'],
      },
      ko: {
        term: '안구 운동',
        anchor: '안구 운동 훈련',
        also: ['사카드', '안구 운동 훈련', '눈 운동'],
      },
    },
  },
  '/drills/reaction-speed/visual-tracking-speed-test': {
    term: 'visual tracking test',
    anchor: 'Visual Tracking Speed Test',
    also: ['visual tracking speed test', 'eye tracking test', 'smooth pursuit test', 'dynamic visual acuity test', 'kinetic interception', 'hand eye coordination test'],
    locales: {
      ja: {
        term: '動体視力 テスト',
        anchor: '動体視力 テスト',
        also: ['動体視力 トレーニング', '動体視力', '視覚追従'],
      },
      ko: {
        term: '동체시력 테스트',
        anchor: '동체시력 테스트',
        also: ['동체시력', '동체시력 훈련', '시각 추적 테스트'],
      },
    },
  },

  // ---------------- VISUAL ----------------
  //
  // `volume: null` = UNMEASURED, not zero — same audit as the MOTOR block above. Every
  // visual entry used to carry a number in a suspiciously tight 1100-1400 band, and none
  // of them had a measurement behind it: scripts/keywords/out/<drill>-raw.json records
  // "impressions": null for all ~430 visual queries run 2026-09-05. Re-measure before
  // treating any of these as a target.
  '/drills/visual/depth-perception/distance-judgment': {
    term: 'depth perception test',
    volume: null,
    anchor: 'Distance Judgment Depth Perception Test',
    also: [
      'depth perception test online',
      'distance judgment test',
      'stereoscopic vision test',
      'howard dolman test',
      'depth perception games',
      'distance estimation test',
      'stereopsis test online',
      'visual depth test',
      'time to contact test',
      'intercept timing drill',
    ],
    locales: {
      ja: {
        term: '深視力 テスト',
        anchor: '深視力 テスト 奥行き知覚 検査',
        also: ['深視力 練習', '立体視 テスト', '三桿法 検査'],
      },
      ko: {
        term: '입체시 검사',
        anchor: '입체시 검사 거리감 테스트',
        also: ['거리감 테스트', '원근감 테스트', '깊이 지각 검사'],
      },
      de: {
        term: 'tiefensehen test',
        anchor: 'Tiefensehen Test Online',
        also: ['räumliches sehen test', 'stereosehen test', 'entfernungsschätzung test'],
      },
    },
  },
  '/drills/visual/reaction-speed/go/no-go': {
    term: 'go no-go test',
    volume: null,
    anchor: 'Go/No-Go Impulse Control Test',
    also: [
      'go no go test online',
      'go no go task',
      'response inhibition test',
      'impulse control test',
      'continuous performance test go no go',
      'sustained attention response task',
      'sart test',
      'trigger discipline drill',
      'donders c reaction',
      'motor inhibition test',
      'executive function go nogo',
    ],
    locales: {
      ja: {
        term: 'ゴーノーゴー 課題',
        anchor: 'ゴーノーゴー課題 反応抑制 テスト',
        also: ['go no-go テスト', '反応抑制 検査', '衝動制御 テスト'],
      },
      ko: {
        term: '고노고 과제',
        anchor: '고노고 과제 반응 억제 검사',
        also: ['반응 억제 테스트', '충동 조절 검사', 'go no-go 검사'],
      },
      de: {
        term: 'go no-go test',
        anchor: 'Go No-Go Test Online',
        also: ['reaktionshemmung test', 'impulskontrolle test', 'kognitive hemmung test'],
      },
    },
  },
  '/drills/visual/reaction-speed/light-reaction': {
    term: 'light reaction test',
    volume: null,
    anchor: 'Light Reaction Reflex Test',
    also: [
      'visual reflex test',
      'visual reaction time test',
      'strobe reaction test',
      'flash reaction test',
      'light reflex test',
      'simple reaction time test',
      'millisecond latency test',
      'visual reflex drill',
      'strobe latency test online',
      'optical reaction test',
      'reflex training drill',
      'visual reaction speed test',
    ],
    locales: {
      ja: {
        term: '光 反応 テスト',
        anchor: '光反応テスト 視覚反射速度 検査',
        also: ['視覚 反応速度 テスト', '反射神経 テスト', 'ストロボ 反応 測定'],
      },
      ko: {
        term: '빛 반응 속도 검사',
        anchor: '빛 반응 속도 검사 시각 반응속도 테스트',
        also: ['시각 반응속도 테스트', '순발력 테스트', '단순 반응 시간 검사'],
      },
      de: {
        term: 'lichtreaktion test',
        anchor: 'Lichtreaktion Test Reflexgeschwindigkeit',
        also: ['optischer reaktionstest', 'reaktionsgeschwindigkeit test', 'einfache reaktionszeit test'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/moving-target': {
    term: 'moving target tracking test',
    volume: null,
    anchor: 'Moving Target Intercept Test',
    also: [
      'moving target test',
      'moving target click test',
      'target tracking drill',
      'kinetic visual tracking game',
      'visual pursuit tracking',
      'kinetic intercept drill',
      'hand-eye tracking game',
      'smooth pursuit eye test',
      'dynamic visual tracking test',
      'moving target aim trainer',
      'visual pursuit aim drill',
      'ballistic intercept test',
    ],
    locales: {
      ja: {
        term: '動体視力 テスト',
        anchor: '動体視力 テスト 動く標的 追従',
        also: ['動く標的 テスト', '追従眼球運動 テスト', '動体視力 トレーニング'],
      },
      ko: {
        term: '동체시력 테스트',
        anchor: '동체시력 테스트 움직이는 타겟 검사',
        also: ['움직이는 타겟 테스트', '시각 추적 검사', '동체시력 훈련'],
      },
      de: {
        term: 'bewegliches ziel test',
        anchor: 'Bewegliches Ziel Test Online',
        also: ['visuelles tracking test', 'zielverfolgung test', 'blickfolgebewegung test'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/multiple-targets': {
    term: 'multiple object tracking test',
    volume: null,
    anchor: 'Multiple Object Tracking Test',
    also: [
      'mot test online',
      'multiple object tracking',
      'visual attention test',
      'multiple object tracking game',
      'divided attention test',
      '3d mot test',
      'dynamic visual tracking test',
      'visual working memory test',
      'neurotracker test',
      'mot training drill',
      'parallel visual tracking',
      'multi target tracking game',
    ],
    locales: {
      ja: {
        term: 'マルチオブジェクトトラッキング テスト',
        anchor: 'マルチオブジェクトトラッキング テスト 複数対象追従',
        also: ['動体追従 テスト', '視覚的注意 テスト', 'MOT テスト'],
      },
      ko: {
        term: '다중 객체 추적 검사',
        anchor: '다중 객체 추적 검사 시각 주의력 테스트',
        also: ['시각 주의력 검사', '움직이는 물체 추적 테스트', 'MOT 검사'],
      },
      de: {
        term: 'multiple object tracking test',
        anchor: 'Multiple Object Tracking Test Online',
        also: ['visuelle aufmerksamkeit test', 'objektverfolgung test', 'mot test online'],
      },
    },
  },
  '/drills/visual/tracking-accuracy/pursuit-tracker': {
    term: 'smooth pursuit test',
    volume: null,
    anchor: 'Smooth Pursuit Tracker',
    also: [
      'smooth pursuit eye movement test',
      'smooth pursuit training',
      'visual pursuit test',
      'smooth pursuit eye tracking',
      'eye tracking accuracy test',
      'dynamic visual pursuit',
      'pursuit aim trainer',
      'visual tracking exercises',
      'smooth pursuit exercises',
      'continuous visual tracking test',
      'smooth pursuit latency',
    ],
    locales: {
      ja: {
        term: '追従眼球運動 テスト',
        anchor: '追従眼球運動 テスト 滑動性追従 検査',
        also: ['滑動性追従眼球運動 検査', '視覚追従 テスト', '動体追従 訓練'],
      },
      ko: {
        term: '추적 안구 운동 검사',
        anchor: '추적 안구 운동 검사 시각 추적 테스트',
        also: ['smooth pursuit 검사', '시각 추적 훈련', '안구 추적 검사'],
      },
      de: {
        term: 'blickfolgebewegungen test',
        anchor: 'Blickfolgebewegungen Test Online',
        also: ['visuelles tracking test', 'augenfolgebewegungen test', 'smooth pursuit test'],
      },
    },
  },
  '/drills/visual/visual-recognition/entropic-grid': {
    // Retargeted 2026-09-06. This drill is NOT a concentration grid: a concentration
    // grid (Schulte table) is a static grid you click in numeric sequence, which is what
    // /drills/cognitive/focus/concentration-grid actually is. This one hunts codes in a
    // 100-cell field that regenerates every 700 ms — a dynamic visual-attention task.
    // Targeting 'concentration grid test' failed the §4.6 honesty gate and collided with
    // that other drill; page 1 for it is also owned by four exact-match domains
    // (concentrationgrid.com/.net, concentrationgrids.com, cgridid.com).
    term: 'visual attention test',
    volume: null,
    anchor: 'Entropic Grid Visual Search',
    also: [
      'selective attention test',
      'visual search test',
      'visual search task',
      'visual scanning test',
      'cognitive focus grid',
      'attention concentration test',
      'visual noise filtering',
      'visual recognition test',
      'feature search test',
      'perceptual speed test',
      'visual cancellation test',
    ],
    locales: {
      ja: {
        term: '集中力グリッド テスト',
        anchor: '集中力グリッド テスト 視覚探索 検査',
        also: ['視覚探索 テスト', '注意集中 検査', '視覚走査 訓練'],
      },
      ko: {
        term: '집중력 그리드 검사',
        anchor: '집중력 그리드 검사 시각 탐색 테스트',
        also: ['시각 탐색 검사', '주의집중력 검사', '시각 스캐닝 훈련'],
      },
      de: {
        term: 'konzentrationsgitter test',
        anchor: 'Konzentrationsgitter Test Online',
        also: ['visuelle suche test', 'suchmatrix test', 'aufmerksamkeitsgitter test'],
      },
    },
  },
  '/drills/visual/visual-recognition/rhythm-anomaly': {
    term: 'visual timing test',
    volume: null,
    anchor: 'Rhythm Anomaly Timing Test',
    also: [
      'temporal discrimination test',
      'visual rhythm test',
      'flicker detection test',
      'pulse detection test',
      'visual temporal perception',
      'critical flicker frequency test',
      'temporal visual acuity',
      'visual rhythm drill',
      'visual anomaly detection',
      'temporal processing test',
      'visual flicker test',
    ],
    locales: {
      ja: {
        term: '視覚リズム テスト',
        anchor: '視覚リズム テスト 時間弁別 検査',
        also: ['時間弁別 検査', 'フリッカー テスト', '周期検出 訓練'],
      },
      ko: {
        term: '시각 리듬 검사',
        anchor: '시각 리듬 검사 시간 변별 테스트',
        also: ['시간 변별 검사', '플리커 검사', '시각 타이밍 훈련'],
      },
      de: {
        term: 'visueller rhythmus test',
        anchor: 'Visueller Rhythmus Test Zeitliche Diskrimination',
        also: ['zeitliche diskrimination test', 'flimmerverschmelzungsfrequenz test', 'flackertest online'],
      },
    },
  },
  '/drills/visual/visual-recognition/visual-search': {
    term: 'visual search test',
    volume: null,
    anchor: 'Conjunctive Visual Search Test',
    also: [
      'conjunctive visual search',
      'visual search task',
      'feature search test',
      'visual scanning test',
      'target discrimination drill',
      'symbol search test',
      'visual inspection test',
      'guided visual search',
      'selective attention search',
      'visual search speed test',
    ],
    locales: {
      ja: {
        term: '視覚探索 テスト',
        anchor: '視覚探索 テスト 結合探索 検査',
        also: ['結合探索 検査', '視覚的注意 テスト', '特徴探索 訓練'],
      },
      ko: {
        term: '시각 탐색 검사',
        anchor: '시각 탐색 검사 결합 탐색 훈련',
        also: ['결합 탐색 검사', '시각적 주의 검사', '특징 탐색 훈련'],
      },
      de: {
        term: 'visuelle suche test',
        anchor: 'Visuelle Suche Test Konjunktive Suche',
        also: ['konjunktive suche test', 'visuelle aufmerksamkeit test', 'merkmalsuche training'],
      },
    },
  },

  // ---------------- VISUAL TRACKING ----------------
  '/drills/visual-tracking/constant-slow-pursuit': {
    term: 'smooth pursuit eye exercise',
    anchor: 'Smooth Pursuit Eye Exercise',
    also: ['constant slow pursuit', 'slow tracking drill', 'eye tracking training', 'gaze stability practice'],
  },
  '/drills/visual-tracking/directional-chaos-pursuit': {
    term: 'erratic motion eye drill',
    anchor: 'Erratic Motion Eye Drill',
    also: ['directional chaos pursuit', 'chaotic tracking practice', 'unpredictable target tracking', 'eye tracking training'],
  },
  '/drills/visual-tracking/dynamic-evasion-pursuit': {
    term: 'reactive eye tracking drill',
    anchor: 'Reactive Eye Tracking Drill',
    also: ['dynamic evasion pursuit', 'evasive target pursuit', 'reaction tracking exercise', 'visual tracking games online'],
  },
  '/drills/visual-tracking/ghosting-suppress-pursuit': {
    term: 'eye fixation stability training',
    anchor: 'Eye Fixation Stability Training',
    also: ['ghosting suppress pursuit', 'ghosting suppression drill', 'gaze steadiness exercise', 'visual fixation practice'],
  },
  '/drills/visual-tracking/infinity-pursuit': {
    term: 'figure-8 eye tracking exercise',
    anchor: 'Figure-8 Eye Tracking Exercise',
    also: ['infinity pursuit', 'infinity loop tracking', 'lazy eight eye drill', 'smooth pursuit training'],
  },
  '/drills/visual-tracking/momentum-teleport-pursuit': {
    term: 'anticipatory eye tracking drill',
    anchor: 'Anticipatory Eye Tracking Drill',
    also: ['momentum teleport pursuit', 'target reacquisition practice', 'momentum prediction drill', 'saccade recovery training'],
  },
  '/drills/visual-tracking/peripheral-ping-pursuit': {
    term: 'peripheral vision training',
    anchor: 'Peripheral Vision Training Drill',
    also: ['peripheral ping pursuit', 'peripheral awareness exercise', 'wide field vision drill', 'peripheral vision test'],
  },
  '/drills/visual-tracking/predictive-pursuit': {
    term: 'predictive eye tracking drill',
    anchor: 'Predictive Eye Tracking Drill',
    also: ['predictive pursuit', 'predictive smooth pursuit', 'occlusion prediction training', 'trajectory anticipation drill', 'eye tracking accuracy'],
  },
  '/drills/visual-tracking/sine-wave-pursuit': {
    term: 'smooth pursuit eye training',
    anchor: 'Sine Wave Pursuit Training',
    also: ['sine wave pursuit', 'sine wave pursuit training', 'wave tracking exercise', 'oscillating target drill', 'eye tracking training'],
  },
  '/drills/visual-tracking/spatial-shift-pursuit': {
    term: 'adaptive eye tracking drill',
    anchor: 'Adaptive Eye Tracking Drill',
    also: ['spatial shift pursuit', 'adaptive eye tracking', 'spatial shift exercise', 'context switching tracking', 'visual adaptation drill'],
  },
  '/drills/visual-tracking/split-screen-tracking': {
    term: 'divided attention eye test',
    anchor: 'Divided Attention Eye Test',
    also: ['split-screen tracking', 'divided attention tracking', 'dual target tracking drill', 'split screen tracking', 'attention splitting exercise'],
  },
  '/drills/visual-tracking/staircase-step': {
    term: 'vertical eye tracking exercise',
    anchor: 'Vertical Eye Tracking Exercise',
    also: ['staircase step', 'vertical zig-zag pursuit', 'staircase step pursuit', 'vertical smooth pursuit', 'vertical zig-zag drill', 'staircase gaze training', 'y-axis eye movement'],
  },
  '/drills/visual-tracking/strobe-prediction-pursuit': {
    term: 'strobe vision training',
    anchor: 'Strobe Vision Training Drill',
    also: ['strobe prediction pursuit', 'stroboscopic training drill', 'strobe eye tracking', 'occluded target tracking', 'intermittent vision practice', 'strobe prediction exercise', 'stroboscopic eye training'],
  },
  '/drills/visual-tracking/triangular-pursuit': {
    term: 'eye tracking accuracy drill',
    anchor: 'Eye Tracking Accuracy Drill',
    also: ['triangular pursuit', 'triangular tracking drill', 'angular pursuit training', 'triangular vector pursuit', 'geometric smooth pursuit', 'triangular path tracking', 'gaze precision exercise'],
  },
  '/drills/visual-tracking/zig-zag-path-pursuit': {
    term: 'eye tracking coordination drill',
    anchor: 'Eye Tracking Coordination Drill',
    also: ['zig-zag path pursuit', 'zig-zag pursuit', 'zigzag pursuit drill', 'zig-zag path tracking', 'saccadic direction drill', 'angular tracking practice', 'acute corner tracking drill'],
  },
};

export function getDrillSeo(href, locale) {
  const entry = DRILL_SEO[href];
  if (!entry) return null;
  if (locale && entry.locales?.[locale]) {
    const loc = entry.locales[locale];
    return {
      term: loc.term || entry.term,
      anchor: loc.anchor || entry.anchor,
      also: loc.also || entry.also,
    };
  }
  return entry;
}
